rules:
  - id: react-dangerouslysetinnerhtml
    pattern: dangerouslySetInnerHTML
    message: "Avoid using dangerouslySetInnerHTML - potential XSS vulnerability"
    languages: [typescript, javascript]
    severity: WARNING
    metadata:
      cwe: "CWE-79: Improper Neutralization of Input During Web Page Generation"
      owasp: "A7: Cross-Site Scripting (XSS)"

  - id: hardcoded-credentials
    patterns:
      - pattern-either:
          - pattern: const $VAR = "$PASSWORD"
          - pattern: const $VAR = "$TOKEN"
          - pattern: const $VAR = "$API_KEY"
    message: "Hardcoded credentials detected - use environment variables"
    languages: [typescript, javascript]
    severity: ERROR

  - id: console-log-in-production
    pattern: console.log(...)
    message: "console.log() found - remove or replace with proper logging"
    languages: [typescript, javascript]
    severity: INFO
    paths:
      exclude:
        - "**/*.test.ts"
        - "**/*.test.tsx"
        - "**/tests/**"

  - id: eval-usage
    pattern: eval(...)
    message: "eval() is dangerous and should be avoided"
    languages: [typescript, javascript]
    severity: ERROR

  - id: localstorage-sensitive-data
    patterns:
      - pattern-either:
          - pattern: localStorage.setItem("password", ...)
          - pattern: localStorage.setItem("token", ...)
          - pattern: localStorage.setItem("apiKey", ...)
          - pattern: sessionStorage.setItem("password", ...)
          - pattern: sessionStorage.setItem("token", ...)
    message: "Sensitive data should not be stored in localStorage/sessionStorage"
    languages: [typescript, javascript]
    severity: WARNING
