# Structurelint Configuration for LangPlug
# Enforces project structure, organization, and architectural integrity
# See: https://github.com/Jonathangadeaharder/structurelint

root: true

# Global rules for all directories
rules:
  # Maximum folder depth to prevent over-nesting
  # Aligned with project standard: max depth of 6-7
  max-depth: { max: 7 }

  # Maximum files per directory to maintain organization
  # Relaxed default - specific overrides below
  max-files-in-dir: { max: 50 }

  # Maximum subdirectories per directory
  max-subdirs: { max: 20 }

  # Disallow version suffixes (enforces "NO VERSION SUFFIXES IN CODE" rule)
  disallowed-patterns:
    - pattern: ".*_(v[0-9]+|new|old|temp|backup|copy)\\.(py|ts|tsx|js|jsx)$"
      message: "Version suffixes (_v2, _new, _old, _temp, _backup) are forbidden. Use git for versioning."
    - pattern: ".*_(v[0-9]+|new|old|temp|backup|copy)/$"
      message: "Version suffixes in directory names are forbidden. Use git for versioning."

# Python Backend Rules
overrides:
  # Root level: Require essential documentation files
  - files: ['.']
    rules:
      max-files-in-dir: { max: 50 }
      max-subdirs: { max: 20 }
      file-existence:
        "CLAUDE.md": "exists:1"
        "README.md": "exists:1"
        ".gitignore": "exists:1"

  # Backend: Python files and directories use snake_case
  - files: ['src/backend/**']
    rules:
      max-depth: { max: 7 }
      max-files-in-dir: { max: 40 }

      naming-convention:
        "*.py": "snake_case"
        "**/": "snake_case"

  # Backend services: Stricter organization
  - files: ['src/backend/services/**']
    rules:
      max-files-in-dir: { max: 25 }
      max-subdirs: { max: 15 }

  # Backend tests: Mirror source structure (higher limits for test files)
  - files: ['src/backend/tests/**']
    rules:
      max-depth: { max: 8 }
      max-files-in-dir: { max: 50 }

      naming-convention:
        "*.py": "snake_case"
        "**/": "snake_case"

  # Backend docs: Allow many documentation files
  - files: ['src/backend/docs/**', 'docs/**']
    rules:
      max-files-in-dir: { max: 50 }

  # TypeScript/React Frontend Rules
  - files: ['src/frontend/**']
    rules:
      max-depth: { max: 7 }
      max-files-in-dir: { max: 35 }

      naming-convention:
        # Files use kebab-case
        "*.ts": "kebab-case"
        "*.js": "kebab-case"
        "**/": "kebab-case"

  # React components can use PascalCase
  - files: ['src/frontend/src/components/**', 'src/frontend/src/screens/**', 'src/frontend/src/contexts/**']
    rules:
      naming-convention:
        "*.tsx": "PascalCase"
        "*.jsx": "PascalCase"

  # Scripts: Use snake_case
  - files: ['scripts/**']
    rules:
      max-files-in-dir: { max: 15 }

      naming-convention:
        "*.py": "snake_case"
        "*.sh": "snake_case"
        "*.bat": "snake_case"
        "**/": "snake_case"

  # Config: kebab-case
  - files: ['config/**']
    rules:
      naming-convention:
        "**/": "kebab-case"

# Ignored paths (build artifacts, caches, dependencies)
ignore:
  - .git
  - .cache
  - .venv
  - api_venv
  - node_modules
  - __pycache__
  - .pytest_cache
  - .mypy_cache
  - .ruff_cache
  - dist
  - build
  - "*.egg-info"
  - .idea
  - .vscode
  - data/downloads
  - data/models
  - data/databases
  - src/backend/logs
  - src/frontend/frontend.log
  - ci-logs
