// This file is auto-generated by @hey-api/openapi-ts

export const $AnswerRequest = {
    properties: {
        session_id: {
            type: 'string',
            title: 'Session Id'
        },
        question_id: {
            type: 'string',
            title: 'Question Id'
        },
        answer: {
            type: 'string',
            title: 'Answer'
        }
    },
    type: 'object',
    required: ['session_id', 'question_id', 'answer'],
    title: 'AnswerRequest',
    description: 'Request model for submitting an answer'
} as const;

export const $BearerResponse = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type'
        }
    },
    type: 'object',
    required: ['access_token', 'token_type'],
    title: 'BearerResponse'
} as const;

export const $Body_auth_jwt_bearer_login_api_auth_login_post = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_auth_jwt_bearer_login_api_auth_login_post'
} as const;

export const $Body_parse_srt_file_api_srt_parse_file_post = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_parse_srt_file_api_srt_parse_file_post'
} as const;

export const $Body_upload_subtitle_api_videos_subtitle_upload_post = {
    properties: {
        subtitle_file: {
            type: 'string',
            format: 'binary',
            title: 'Subtitle File'
        }
    },
    type: 'object',
    required: ['subtitle_file'],
    title: 'Body_upload_subtitle_api_videos_subtitle_upload_post'
} as const;

export const $Body_upload_video_generic_api_videos_upload_post = {
    properties: {
        video_file: {
            type: 'string',
            format: 'binary',
            title: 'Video File'
        }
    },
    type: 'object',
    required: ['video_file'],
    title: 'Body_upload_video_generic_api_videos_upload_post'
} as const;

export const $Body_upload_video_to_series_api_videos_upload__series__post = {
    properties: {
        video_file: {
            type: 'string',
            format: 'binary',
            title: 'Video File'
        }
    },
    type: 'object',
    required: ['video_file'],
    title: 'Body_upload_video_to_series_api_videos_upload__series__post'
} as const;

export const $BulkMarkRequest = {
    properties: {
        level: {
            type: 'string',
            pattern: '^(A1|A2|B1|B2|C1|C2)$',
            title: 'Level',
            description: 'CEFR difficulty level to mark (A1, A2, B1, B2, C1, C2)'
        },
        known: {
            type: 'boolean',
            title: 'Known',
            description: 'Whether to mark all words in the level as known (true) or unknown (false)'
        }
    },
    type: 'object',
    required: ['level', 'known'],
    title: 'BulkMarkRequest'
} as const;

export const $ChunkProcessingRequest = {
    properties: {
        video_path: {
            type: 'string',
            minLength: 1,
            title: 'Video Path',
            description: 'Path to the video file to process'
        },
        start_time: {
            type: 'number',
            minimum: 0,
            title: 'Start Time',
            description: 'Start time of the chunk in seconds'
        },
        end_time: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'End Time',
            description: 'End time of the chunk in seconds'
        }
    },
    type: 'object',
    required: ['video_path', 'start_time', 'end_time'],
    title: 'ChunkProcessingRequest',
    example: {
        end_time: 180,
        start_time: 120.5,
        video_path: '/videos/Superstore/S01/E01.mp4'
    }
} as const;

export const $ConvertToSRTRequest = {
    properties: {
        segments: {
            items: {
                '$ref': '#/components/schemas/SRTSegmentResponse'
            },
            type: 'array',
            title: 'Segments'
        }
    },
    type: 'object',
    required: ['segments'],
    title: 'ConvertToSRTRequest',
    description: 'Request model for converting segments to SRT format.'
} as const;

export const $DailyProgress = {
    properties: {
        date: {
            type: 'string',
            title: 'Date'
        },
        videos_watched: {
            type: 'integer',
            title: 'Videos Watched',
            default: 0
        },
        watch_time: {
            type: 'number',
            title: 'Watch Time',
            default: 0
        },
        vocabulary_learned: {
            type: 'integer',
            title: 'Vocabulary Learned',
            default: 0
        },
        goals_completed: {
            type: 'integer',
            title: 'Goals Completed',
            default: 0
        },
        experience_gained: {
            type: 'integer',
            title: 'Experience Gained',
            default: 0
        }
    },
    type: 'object',
    required: ['date'],
    title: 'DailyProgress',
    description: 'Daily progress model'
} as const;

export const $ErrorModel = {
    properties: {
        detail: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                }
            ],
            title: 'Detail'
        }
    },
    type: 'object',
    required: ['detail'],
    title: 'ErrorModel'
} as const;

export const $FilterRequest = {
    properties: {
        video_path: {
            type: 'string',
            minLength: 1,
            title: 'Video Path',
            description: 'Path to the video file to filter subtitles for'
        }
    },
    type: 'object',
    required: ['video_path'],
    title: 'FilterRequest'
} as const;

export const $FullPipelineRequest = {
    properties: {
        video_path: {
            type: 'string',
            minLength: 1,
            title: 'Video Path',
            description: 'Path to the video file to process'
        },
        source_lang: {
            type: 'string',
            maxLength: 5,
            minLength: 2,
            pattern: '^[a-z]{2}(-[A-Z]{2})?$',
            title: 'Source Lang',
            description: "Source language code (e.g., 'de', 'en-US')",
            default: 'de'
        },
        target_lang: {
            type: 'string',
            maxLength: 5,
            minLength: 2,
            pattern: '^[a-z]{2}(-[A-Z]{2})?$',
            title: 'Target Lang',
            description: "Target language code (e.g., 'en', 'de-DE')",
            default: 'en'
        }
    },
    type: 'object',
    required: ['video_path'],
    title: 'FullPipelineRequest'
} as const;

export const $GameSession = {
    properties: {
        session_id: {
            type: 'string',
            title: 'Session Id'
        },
        user_id: {
            type: 'string',
            title: 'User Id'
        },
        game_type: {
            type: 'string',
            title: 'Game Type'
        },
        difficulty: {
            type: 'string',
            title: 'Difficulty',
            default: 'intermediate'
        },
        video_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Video Id'
        },
        start_time: {
            type: 'string',
            format: 'date-time',
            title: 'Start Time'
        },
        end_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Time'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'active'
        },
        score: {
            type: 'integer',
            title: 'Score',
            default: 0
        },
        max_score: {
            type: 'integer',
            title: 'Max Score',
            default: 100
        },
        questions_answered: {
            type: 'integer',
            title: 'Questions Answered',
            default: 0
        },
        correct_answers: {
            type: 'integer',
            title: 'Correct Answers',
            default: 0
        },
        current_question: {
            type: 'integer',
            title: 'Current Question',
            default: 0
        },
        total_questions: {
            type: 'integer',
            title: 'Total Questions',
            default: 10
        },
        session_data: {
            additionalProperties: true,
            type: 'object',
            title: 'Session Data',
            default: {}
        }
    },
    type: 'object',
    required: ['session_id', 'user_id', 'game_type', 'start_time'],
    title: 'GameSession',
    description: 'Game session model'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $LanguagePreferences = {
    properties: {
        native_language: {
            type: 'string',
            title: 'Native Language'
        },
        target_language: {
            type: 'string',
            title: 'Target Language'
        }
    },
    type: 'object',
    required: ['native_language', 'target_language'],
    title: 'LanguagePreferences',
    description: 'Language preference update model'
} as const;

export const $LogBatch = {
    properties: {
        entries: {
            items: {
                '$ref': '#/components/schemas/LogEntry'
            },
            type: 'array',
            title: 'Entries'
        },
        client_id: {
            type: 'string',
            title: 'Client Id',
            default: 'frontend'
        }
    },
    type: 'object',
    required: ['entries'],
    title: 'LogBatch'
} as const;

export const $LogEntry = {
    properties: {
        timestamp: {
            type: 'string',
            title: 'Timestamp'
        },
        level: {
            type: 'string',
            title: 'Level'
        },
        component: {
            type: 'string',
            title: 'Component'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        data: {
            type: 'string',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['timestamp', 'level', 'component', 'message'],
    title: 'LogEntry'
} as const;

export const $MarkKnownRequest = {
    properties: {
        word: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Word',
            description: 'The word to mark as known/unknown'
        },
        known: {
            type: 'boolean',
            title: 'Known',
            description: 'Whether to mark the word as known (true) or unknown (false)'
        }
    },
    type: 'object',
    required: ['word', 'known'],
    title: 'MarkKnownRequest'
} as const;

export const $ParseSRTRequest = {
    properties: {
        content: {
            type: 'string',
            title: 'Content'
        }
    },
    type: 'object',
    required: ['content'],
    title: 'ParseSRTRequest',
    description: 'Request model for parsing SRT content.'
} as const;

export const $ParseSRTResponse = {
    properties: {
        segments: {
            items: {
                '$ref': '#/components/schemas/SRTSegmentResponse'
            },
            type: 'array',
            title: 'Segments'
        },
        total_segments: {
            type: 'integer',
            title: 'Total Segments'
        },
        duration: {
            type: 'number',
            title: 'Duration'
        }
    },
    type: 'object',
    required: ['segments', 'total_segments', 'duration'],
    title: 'ParseSRTResponse',
    description: 'Response model for parsed SRT data.'
} as const;

export const $ProcessingStatus = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        progress: {
            type: 'number',
            title: 'Progress'
        },
        current_step: {
            type: 'string',
            title: 'Current Step'
        },
        message: {
            type: 'string',
            title: 'Message',
            default: ''
        },
        subtitle_path: {
            type: 'string',
            title: 'Subtitle Path',
            default: ''
        }
    },
    type: 'object',
    required: ['status', 'progress', 'current_step'],
    title: 'ProcessingStatus'
} as const;

export const $SRTSegmentResponse = {
    properties: {
        index: {
            type: 'integer',
            title: 'Index'
        },
        start_time: {
            type: 'number',
            title: 'Start Time'
        },
        end_time: {
            type: 'number',
            title: 'End Time'
        },
        text: {
            type: 'string',
            title: 'Text'
        },
        original_text: {
            type: 'string',
            title: 'Original Text',
            default: ''
        },
        translation: {
            type: 'string',
            title: 'Translation',
            default: ''
        }
    },
    type: 'object',
    required: ['index', 'start_time', 'end_time', 'text'],
    title: 'SRTSegmentResponse',
    description: 'Response model for SRT segment data.'
} as const;

export const $StartGameRequest = {
    properties: {
        game_type: {
            type: 'string',
            title: 'Game Type'
        },
        difficulty: {
            type: 'string',
            title: 'Difficulty',
            default: 'intermediate'
        },
        video_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Video Id'
        },
        total_questions: {
            type: 'integer',
            title: 'Total Questions',
            default: 10
        }
    },
    type: 'object',
    required: ['game_type'],
    title: 'StartGameRequest',
    description: 'Request model for starting a game session'
} as const;

export const $TranscribeRequest = {
    properties: {
        video_path: {
            type: 'string',
            minLength: 1,
            title: 'Video Path',
            description: 'Path to the video file to transcribe'
        }
    },
    type: 'object',
    required: ['video_path'],
    title: 'TranscribeRequest'
} as const;

export const $TranslateRequest = {
    properties: {
        video_path: {
            type: 'string',
            minLength: 1,
            title: 'Video Path',
            description: 'Path to the video file to translate subtitles for'
        },
        source_lang: {
            type: 'string',
            maxLength: 5,
            minLength: 2,
            pattern: '^[a-z]{2}(-[A-Z]{2})?$',
            title: 'Source Lang',
            description: "Source language code (e.g., 'de', 'en-US')"
        },
        target_lang: {
            type: 'string',
            maxLength: 5,
            minLength: 2,
            pattern: '^[a-z]{2}(-[A-Z]{2})?$',
            title: 'Target Lang',
            description: "Target language code (e.g., 'en', 'de-DE')"
        }
    },
    type: 'object',
    required: ['video_path', 'source_lang', 'target_lang'],
    title: 'TranslateRequest'
} as const;

export const $UserCreate = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser',
            default: false
        },
        is_verified: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Verified',
            default: false
        },
        username: {
            type: 'string',
            title: 'Username'
        }
    },
    type: 'object',
    required: ['email', 'password', 'username'],
    title: 'UserCreate'
} as const;

export const $UserProfile = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        is_admin: {
            type: 'boolean',
            title: 'Is Admin'
        },
        created_at: {
            type: 'string',
            title: 'Created At'
        },
        last_login: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Login'
        },
        native_language: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Native Language'
        },
        target_language: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Target Language'
        }
    },
    type: 'object',
    required: ['id', 'username', 'is_admin', 'created_at', 'native_language', 'target_language'],
    title: 'UserProfile',
    description: 'User profile response model'
} as const;

export const $UserProgress = {
    properties: {
        user_id: {
            type: 'string',
            title: 'User Id'
        },
        total_videos_watched: {
            type: 'integer',
            title: 'Total Videos Watched',
            default: 0
        },
        total_watch_time: {
            type: 'number',
            title: 'Total Watch Time',
            default: 0
        },
        vocabulary_learned: {
            type: 'integer',
            title: 'Vocabulary Learned',
            default: 0
        },
        current_streak: {
            type: 'integer',
            title: 'Current Streak',
            default: 0
        },
        longest_streak: {
            type: 'integer',
            title: 'Longest Streak',
            default: 0
        },
        level: {
            type: 'string',
            title: 'Level',
            default: 'Beginner'
        },
        experience_points: {
            type: 'integer',
            title: 'Experience Points',
            default: 0
        },
        daily_goals_completed: {
            type: 'integer',
            title: 'Daily Goals Completed',
            default: 0
        },
        weekly_goals_completed: {
            type: 'integer',
            title: 'Weekly Goals Completed',
            default: 0
        },
        last_activity: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Activity'
        },
        achievements: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Achievements',
            default: []
        },
        learning_stats: {
            additionalProperties: true,
            type: 'object',
            title: 'Learning Stats',
            default: {}
        }
    },
    type: 'object',
    required: ['user_id'],
    title: 'UserProgress',
    description: 'User progress model'
} as const;

export const $UserRead = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        last_login: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Login'
        }
    },
    type: 'object',
    required: ['id', 'email', 'is_active', 'is_superuser', 'is_verified', 'username', 'created_at', 'last_login'],
    title: 'UserRead'
} as const;

export const $UserResponse = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id',
            description: 'Unique user identifier (UUID)'
        },
        username: {
            type: 'string',
            maxLength: 50,
            minLength: 3,
            title: 'Username',
            description: 'Username'
        },
        email: {
            type: 'string',
            title: 'Email',
            description: 'User email address'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            description: 'Whether user has superuser privileges'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            description: 'Whether user account is active'
        },
        created_at: {
            type: 'string',
            title: 'Created At',
            description: 'Account creation timestamp (ISO format)'
        },
        last_login: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Login',
            description: 'Last login timestamp (ISO format)'
        }
    },
    type: 'object',
    required: ['id', 'username', 'email', 'is_superuser', 'is_active', 'created_at'],
    title: 'UserResponse',
    example: {
        created_at: '2024-01-15T10:30:00Z',
        email: 'john_doe@example.com',
        id: '550e8400-e29b-41d4-a716-446655440000',
        is_active: true,
        is_superuser: false,
        last_login: '2024-01-20T14:45:00Z',
        username: 'john_doe'
    }
} as const;

export const $UserSettings = {
    properties: {
        theme: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Theme',
            default: 'light'
        },
        notifications_enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notifications Enabled',
            default: true
        },
        auto_play: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Auto Play',
            default: true
        },
        subtitle_size: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Subtitle Size',
            default: 'medium'
        },
        playback_speed: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Playback Speed',
            default: 1
        },
        vocabulary_difficulty: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vocabulary Difficulty',
            default: 'intermediate'
        },
        daily_goal: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Daily Goal',
            default: 10
        },
        language_preferences: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/LanguagePreferences'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'UserSettings',
    description: 'User settings model'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const $VideoInfo = {
    properties: {
        series: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Series',
            description: 'Name of the TV series'
        },
        season: {
            type: 'string',
            maxLength: 20,
            minLength: 1,
            title: 'Season',
            description: "Season identifier (e.g., 'S01', 'Season 1')"
        },
        episode: {
            type: 'string',
            maxLength: 20,
            minLength: 1,
            title: 'Episode',
            description: "Episode identifier (e.g., 'E01', 'Episode 1')"
        },
        title: {
            type: 'string',
            maxLength: 200,
            minLength: 1,
            title: 'Title',
            description: 'Episode title'
        },
        path: {
            type: 'string',
            minLength: 1,
            title: 'Path',
            description: 'File system path to the video file'
        },
        has_subtitles: {
            type: 'boolean',
            title: 'Has Subtitles',
            description: 'Whether subtitles are available for this video'
        },
        duration: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration',
            description: 'Video duration in seconds'
        }
    },
    type: 'object',
    required: ['series', 'season', 'episode', 'title', 'path', 'has_subtitles'],
    title: 'VideoInfo',
    example: {
        duration: 1320.5,
        episode: 'E01',
        has_subtitles: true,
        path: '/videos/Superstore/S01/E01.mp4',
        season: 'S01',
        series: 'Superstore',
        title: 'Pilot'
    }
} as const;

export const $VocabularyStats = {
    properties: {
        levels: {
            additionalProperties: {
                additionalProperties: {
                    type: 'integer'
                },
                type: 'object'
            },
            type: 'object',
            title: 'Levels',
            description: 'Statistics by CEFR level with total and known counts'
        },
        total_words: {
            type: 'integer',
            minimum: 0,
            title: 'Total Words',
            description: 'Total number of vocabulary words across all levels'
        },
        total_known: {
            type: 'integer',
            minimum: 0,
            title: 'Total Known',
            description: 'Total number of known words across all levels'
        }
    },
    type: 'object',
    required: ['levels', 'total_words', 'total_known'],
    title: 'VocabularyStats',
    example: {
        levels: {
            A1: {
                known: 80,
                total: 100
            },
            A2: {
                known: 60,
                total: 150
            },
            B1: {
                known: 40,
                total: 200
            }
        },
        total_known: 180,
        total_words: 450
    }
} as const;

export const $VocabularyWord = {
    properties: {
        word: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Word',
            description: 'The vocabulary word'
        },
        definition: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Definition',
            description: 'Definition of the word'
        },
        difficulty_level: {
            type: 'string',
            pattern: '^(A1|A2|B1|B2|C1|C2)$',
            title: 'Difficulty Level',
            description: 'CEFR difficulty level (A1, A2, B1, B2, C1, C2)'
        },
        known: {
            type: 'boolean',
            title: 'Known',
            description: 'Whether the user knows this word',
            default: false
        }
    },
    type: 'object',
    required: ['word', 'difficulty_level'],
    title: 'VocabularyWord'
} as const;