// This file is auto-generated by @hey-api/openapi-ts

/**
 * Request model for submitting an answer
 */
export type AnswerRequest = {
    session_id: string;
    question_id: string;
    question_type?: string;
    user_answer: string;
    correct_answer?: string | null;
    points?: number;
};

export type BearerResponse = {
    access_token: string;
    token_type: string;
};

export type Body_auth_jwt_bearer_login_api_auth_login_post = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type Body_parse_srt_file_api_srt_parse_file_post = {
    file: (Blob | File);
};

export type Body_upload_subtitle_api_videos_subtitle_upload_post = {
    subtitle_file: (Blob | File);
};

export type Body_upload_video_generic_api_videos_upload_post = {
    video_file: (Blob | File);
};

export type Body_upload_video_to_series_api_videos_upload__series__post = {
    video_file: (Blob | File);
};

/**
 * Request to bulk mark words as known/unknown
 */
export type BulkMarkRequest = {
    /**
     * CEFR difficulty level to mark
     */
    level: string;
    /**
     * Target language code (de, es, en, etc.)
     */
    target_language: string;
    /**
     * Whether to mark all words as known (true) or unknown (false)
     */
    known: boolean;
};

export type ChunkProcessingRequest = {
    /**
     * Path to the video file to process
     */
    video_path: string;
    /**
     * Start time of the chunk in seconds
     */
    start_time: number;
    /**
     * End time of the chunk in seconds
     */
    end_time: number;
};

/**
 * Request model for converting segments to SRT format.
 */
export type ConvertToSRTRequest = {
    segments: Array<SRTSegmentResponse>;
};

/**
 * Daily progress model
 */
export type DailyProgress = {
    date: string;
    videos_watched?: number;
    watch_time?: number;
    vocabulary_learned?: number;
    goals_completed?: number;
    experience_gained?: number;
};

export type ErrorModel = {
    detail: string | {
    [key: string]: (string);
};
};

export type FilterRequest = {
    /**
     * Path to the video file to filter subtitles for
     */
    video_path: string;
};

export type FullPipelineRequest = {
    /**
     * Path to the video file to process
     */
    video_path: string;
    /**
     * Source language code (e.g., 'de', 'en-US')
     */
    source_lang?: string;
    /**
     * Target language code (e.g., 'en', 'de-DE')
     */
    target_lang?: string;
};

/**
 * Valid difficulty levels
 */
export type GameDifficulty = 'beginner' | 'intermediate' | 'advanced';

/**
 * Game session model
 */
export type GameSession = {
    session_id: string;
    user_id: string;
    game_type: string;
    difficulty?: string;
    video_id?: string | null;
    start_time: string;
    end_time?: string | null;
    status?: string;
    score?: number;
    max_score?: number;
    questions_answered?: number;
    correct_answers?: number;
    current_question?: number;
    total_questions?: number;
    session_data?: {
        [key: string]: unknown;
    };
};

/**
 * Valid game types
 */
export type GameType = 'vocabulary' | 'listening' | 'comprehension';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Language preference update model
 */
export type LanguagePreferences = {
    native_language: string;
    target_language: string;
};

/**
 * Response containing supported languages
 */
export type LanguagesResponse = {
    /**
     * List of supported languages
     */
    languages: Array<SupportedLanguage>;
};

/**
 * Request to mark a word as known/unknown
 */
export type MarkKnownRequest = {
    /**
     * Unique concept identifier
     */
    concept_id: string;
    /**
     * Whether to mark the word as known (true) or unknown (false)
     */
    known: boolean;
};

/**
 * Request model for parsing SRT content.
 */
export type ParseSRTRequest = {
    content: string;
};

/**
 * Response model for parsed SRT data.
 */
export type ParseSRTResponse = {
    segments: Array<SRTSegmentResponse>;
    total_segments: number;
    duration: number;
};

export type ProcessingStatus = {
    status: string;
    progress: number;
    current_step: string;
    message?: string;
    subtitle_path?: string;
};

/**
 * Response model for SRT segment data.
 */
export type SRTSegmentResponse = {
    index: number;
    start_time: number;
    end_time: number;
    text: string;
    original_text?: string;
    translation?: string;
};

/**
 * Request model for starting a game session
 */
export type StartGameRequest = {
    game_type: GameType;
    difficulty?: GameDifficulty;
    video_id?: string | null;
    total_questions?: number;
};

/**
 * Supported language information
 */
export type SupportedLanguage = {
    /**
     * Language code (de, es, en, etc.)
     */
    code: string;
    /**
     * Language name in English
     */
    name: string;
    /**
     * Language name in native script
     */
    native_name?: string | null;
    /**
     * Whether the language is currently supported
     */
    is_active?: boolean;
};

export type TranscribeRequest = {
    /**
     * Path to the video file to transcribe
     */
    video_path: string;
};

export type TranslateRequest = {
    /**
     * Path to the video file to translate subtitles for
     */
    video_path: string;
    /**
     * Source language code (e.g., 'de', 'en-US')
     */
    source_lang: string;
    /**
     * Target language code (e.g., 'en', 'de-DE')
     */
    target_lang: string;
};

export type UserCreate = {
    email: string;
    password: string;
    is_active?: boolean | null;
    is_superuser?: boolean | null;
    is_verified?: boolean | null;
    username: string;
};

/**
 * User profile response model
 */
export type UserProfile = {
    id: string;
    username: string;
    is_admin: boolean;
    created_at: string;
    last_login?: string | null;
    native_language: {
        [key: string]: (string);
    };
    target_language: {
        [key: string]: (string);
    };
};

/**
 * User progress model
 */
export type UserProgress = {
    user_id: string;
    total_videos_watched?: number;
    total_watch_time?: number;
    vocabulary_learned?: number;
    current_streak?: number;
    longest_streak?: number;
    level?: string;
    experience_points?: number;
    daily_goals_completed?: number;
    weekly_goals_completed?: number;
    last_activity?: string | null;
    achievements?: Array<(string)>;
    learning_stats?: {
        [key: string]: unknown;
    };
};

export type UserRead = {
    id: string;
    email: string;
    is_active: boolean;
    is_superuser: boolean;
    is_verified: boolean;
    username: string;
    created_at: string;
    last_login: string | null;
};

export type UserResponse = {
    /**
     * Unique user identifier (UUID)
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * User email address
     */
    email: string;
    /**
     * Whether user has superuser privileges
     */
    is_superuser: boolean;
    /**
     * Whether user account is active
     */
    is_active: boolean;
    /**
     * Account creation timestamp (ISO format)
     */
    created_at: string;
    /**
     * Last login timestamp (ISO format)
     */
    last_login?: string | null;
};

/**
 * User settings model
 */
export type UserSettings = {
    theme?: string | null;
    notifications_enabled?: boolean | null;
    auto_play?: boolean | null;
    subtitle_size?: string | null;
    playback_speed?: number | null;
    vocabulary_difficulty?: string | null;
    daily_goal?: number | null;
    language_preferences?: LanguagePreferences | null;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type VideoInfo = {
    /**
     * Name of the TV series
     */
    series: string;
    /**
     * Season identifier (e.g., 'S01', 'Season 1')
     */
    season: string;
    /**
     * Episode identifier (e.g., 'E01', 'Episode 1')
     */
    episode: string;
    /**
     * Episode title
     */
    title: string;
    /**
     * File system path to the video file
     */
    path: string;
    /**
     * Whether subtitles are available for this video
     */
    has_subtitles: boolean;
    /**
     * Video duration in seconds
     */
    duration?: number | null;
};

/**
 * Vocabulary statistics across all levels
 */
export type VocabularyStats = {
    /**
     * Statistics by CEFR level with total and known counts
     */
    levels: {
        [key: string]: {
            [key: string]: (number);
        };
    };
    /**
     * Target language code
     */
    target_language: string;
    /**
     * Translation language code
     */
    translation_language?: string | null;
    /**
     * Total number of vocabulary words across all levels
     */
    total_words: number;
    /**
     * Total number of known words across all levels
     */
    total_known: number;
};

/**
 * Single vocabulary word with translations
 */
export type VocabularyWord = {
    /**
     * Unique concept identifier
     */
    concept_id: string;
    /**
     * The vocabulary word in target language
     */
    word: string;
    /**
     * Translation in user's preferred language
     */
    translation?: string | null;
    /**
     * Base form of the word
     */
    lemma?: string | null;
    /**
     * CEFR difficulty level
     */
    difficulty_level: string;
    /**
     * Part of speech (noun, verb, adjective, etc.)
     */
    semantic_category?: string | null;
    /**
     * Domain category (education, technology, etc.)
     */
    domain?: string | null;
    /**
     * Gender (der/die/das for German, el/la for Spanish)
     */
    gender?: string | null;
    /**
     * Plural form if applicable
     */
    plural_form?: string | null;
    /**
     * IPA or phonetic representation
     */
    pronunciation?: string | null;
    /**
     * Grammar notes, usage notes, etc.
     */
    notes?: string | null;
    /**
     * Whether the user knows this word
     */
    known?: boolean;
};

export type HealthCheckHealthGetResponse = unknown;

export type TestEndpointTestGetResponse = unknown;

export type AuthJwtBearerLoginApiAuthLoginPostData = {
    formData: Body_auth_jwt_bearer_login_api_auth_login_post;
};

export type AuthJwtBearerLoginApiAuthLoginPostResponse = BearerResponse;

export type AuthJwtBearerLogoutApiAuthLogoutPostResponse = unknown;

export type RegisterRegisterApiAuthRegisterPostData = {
    requestBody: UserCreate;
};

export type RegisterRegisterApiAuthRegisterPostResponse = UserRead;

export type AuthGetCurrentUserApiAuthMeGetResponse = UserResponse;

export type GetVideosApiVideosGetResponse = Array<VideoInfo>;

export type GetSubtitlesApiVideosSubtitlesSubtitlePathGetData = {
    subtitlePath: string;
};

export type GetSubtitlesApiVideosSubtitlesSubtitlePathGetResponse = unknown;

export type StreamVideoApiVideosSeriesEpisodeGetData = {
    episode: string;
    series: string;
};

export type StreamVideoApiVideosSeriesEpisodeGetResponse = unknown;

export type UploadSubtitleApiVideosSubtitleUploadPostData = {
    formData: Body_upload_subtitle_api_videos_subtitle_upload_post;
    videoPath: string;
};

export type UploadSubtitleApiVideosSubtitleUploadPostResponse = unknown;

export type ScanVideosApiVideosScanPostResponse = unknown;

export type GetUserVideosApiVideosUserGetResponse = Array<{
    [key: string]: unknown;
}>;

export type GetVideoVocabularyApiVideosVideoIdVocabularyGetData = {
    videoId: string;
};

export type GetVideoVocabularyApiVideosVideoIdVocabularyGetResponse = Array<VocabularyWord>;

export type GetVideoStatusApiVideosVideoIdStatusGetData = {
    videoId: string;
};

export type GetVideoStatusApiVideosVideoIdStatusGetResponse = ProcessingStatus;

export type UploadVideoGenericApiVideosUploadPostData = {
    formData: Body_upload_video_generic_api_videos_upload_post;
    series?: string;
};

export type UploadVideoGenericApiVideosUploadPostResponse = unknown;

export type UploadVideoToSeriesApiVideosUploadSeriesPostData = {
    formData: Body_upload_video_to_series_api_videos_upload__series__post;
    series: string;
};

export type UploadVideoToSeriesApiVideosUploadSeriesPostResponse = unknown;

export type ProcessChunkApiProcessChunkPostData = {
    requestBody: ChunkProcessingRequest;
};

export type ProcessChunkApiProcessChunkPostResponse = unknown;

export type TranscribeVideoApiProcessTranscribePostData = {
    requestBody: TranscribeRequest;
};

export type TranscribeVideoApiProcessTranscribePostResponse = unknown;

export type FilterSubtitlesApiProcessFilterSubtitlesPostData = {
    requestBody: FilterRequest;
};

export type FilterSubtitlesApiProcessFilterSubtitlesPostResponse = unknown;

export type TranslateSubtitlesApiProcessTranslateSubtitlesPostData = {
    requestBody: TranslateRequest;
};

export type TranslateSubtitlesApiProcessTranslateSubtitlesPostResponse = unknown;

export type PrepareEpisodeApiProcessPrepareEpisodePostData = {
    requestBody: TranscribeRequest;
};

export type PrepareEpisodeApiProcessPrepareEpisodePostResponse = unknown;

export type FullPipelineApiProcessFullPipelinePostData = {
    requestBody: FullPipelineRequest;
};

export type FullPipelineApiProcessFullPipelinePostResponse = unknown;

export type GetTaskProgressApiProcessProgressTaskIdGetData = {
    taskId: string;
};

export type GetTaskProgressApiProcessProgressTaskIdGetResponse = unknown;

export type GetSupportedLanguagesApiVocabularyLanguagesGetResponse = LanguagesResponse;

export type GetVocabularyStatsApiVocabularyStatsGetData = {
    /**
     * Target language code
     */
    targetLanguage?: string;
    /**
     * Translation language code
     */
    translationLanguage?: string | null;
};

export type GetVocabularyStatsApiVocabularyStatsGetResponse = VocabularyStats;

export type GetVocabularyLevelApiVocabularyLibraryLevelGetData = {
    level: string;
    /**
     * Maximum number of words to return
     */
    limit?: number;
    /**
     * Target language code
     */
    targetLanguage?: string;
    /**
     * Translation language code
     */
    translationLanguage?: string | null;
};

export type GetVocabularyLevelApiVocabularyLibraryLevelGetResponse = unknown;

export type MarkWordKnownApiVocabularyMarkKnownPostData = {
    requestBody: MarkKnownRequest;
};

export type MarkWordKnownApiVocabularyMarkKnownPostResponse = unknown;

export type BulkMarkLevelApiVocabularyLibraryBulkMarkPostData = {
    requestBody: BulkMarkRequest;
};

export type BulkMarkLevelApiVocabularyLibraryBulkMarkPostResponse = unknown;

export type GetTestDataApiVocabularyTestDataGetResponse = unknown;

export type GetBlockingWordsApiVocabularyBlockingWordsGetData = {
    /**
     * Path to the video file
     */
    videoPath: string;
};

export type GetBlockingWordsApiVocabularyBlockingWordsGetResponse = unknown;

export type ProfileGetApiProfileGetResponse = UserProfile;

export type ProfileGetSupportedLanguagesApiProfileLanguagesGetResponse = {
    [key: string]: {
        [key: string]: (string);
    };
};

export type ProfileUpdateLanguagesApiProfileLanguagesPutData = {
    requestBody: LanguagePreferences;
};

export type ProfileUpdateLanguagesApiProfileLanguagesPutResponse = {
    [key: string]: unknown;
};

export type ProfileGetSettingsApiProfileSettingsGetResponse = UserSettings;

export type ProfileUpdateSettingsApiProfileSettingsPutData = {
    requestBody: UserSettings;
};

export type ProfileUpdateSettingsApiProfileSettingsPutResponse = UserSettings;

export type ProgressGetUserApiProgressUserGetResponse = UserProgress;

export type ProgressUpdateUserApiProgressUpdatePostData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type ProgressUpdateUserApiProgressUpdatePostResponse = unknown;

export type ProgressGetDailyApiProgressDailyGetData = {
    days?: number;
};

export type ProgressGetDailyApiProgressDailyGetResponse = Array<DailyProgress>;

export type GameStartSessionApiGameStartPostData = {
    requestBody: StartGameRequest;
};

export type GameStartSessionApiGameStartPostResponse = GameSession;

export type GameGetSessionApiGameSessionSessionIdGetData = {
    sessionId: string;
};

export type GameGetSessionApiGameSessionSessionIdGetResponse = GameSession;

export type GameSubmitAnswerApiGameAnswerPostData = {
    requestBody: AnswerRequest;
};

export type GameSubmitAnswerApiGameAnswerPostResponse = unknown;

export type GameGetUserSessionsApiGameSessionsGetData = {
    limit?: number;
};

export type GameGetUserSessionsApiGameSessionsGetResponse = Array<GameSession>;

export type ParseSrtContentApiSrtParsePostData = {
    requestBody: ParseSRTRequest;
};

export type ParseSrtContentApiSrtParsePostResponse = ParseSRTResponse;

export type ParseSrtFileApiSrtParseFilePostData = {
    formData: Body_parse_srt_file_api_srt_parse_file_post;
};

export type ParseSrtFileApiSrtParseFilePostResponse = unknown;

export type ConvertToSrtApiSrtConvertToSrtPostData = {
    requestBody: ConvertToSRTRequest;
};

export type ConvertToSrtApiSrtConvertToSrtPostResponse = unknown;

export type ValidateSrtContentApiSrtValidateGetData = {
    content: string;
};

export type ValidateSrtContentApiSrtValidateGetResponse = unknown;

export type $OpenApiTs = {
    '/health': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/test': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/api/auth/login': {
        post: {
            req: AuthJwtBearerLoginApiAuthLoginPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: BearerResponse;
                /**
                 * Bad Request
                 */
                400: ErrorModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/auth/logout': {
        post: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
            };
        };
    };
    '/api/auth/register': {
        post: {
            req: RegisterRegisterApiAuthRegisterPostData;
            res: {
                /**
                 * Successful Response
                 */
                201: UserRead;
                /**
                 * Bad Request
                 */
                400: ErrorModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/auth/me': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: UserResponse;
            };
        };
    };
    '/api/videos': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<VideoInfo>;
            };
        };
    };
    '/api/videos/subtitles/{subtitle_path}': {
        get: {
            req: GetSubtitlesApiVideosSubtitlesSubtitlePathGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/videos/{series}/{episode}': {
        get: {
            req: StreamVideoApiVideosSeriesEpisodeGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/videos/subtitle/upload': {
        post: {
            req: UploadSubtitleApiVideosSubtitleUploadPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/videos/scan': {
        post: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/api/videos/user': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<{
                    [key: string]: unknown;
                }>;
            };
        };
    };
    '/api/videos/{video_id}/vocabulary': {
        get: {
            req: GetVideoVocabularyApiVideosVideoIdVocabularyGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<VocabularyWord>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/videos/{video_id}/status': {
        get: {
            req: GetVideoStatusApiVideosVideoIdStatusGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: ProcessingStatus;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/videos/upload': {
        post: {
            req: UploadVideoGenericApiVideosUploadPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/videos/upload/{series}': {
        post: {
            req: UploadVideoToSeriesApiVideosUploadSeriesPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/process/chunk': {
        post: {
            req: ProcessChunkApiProcessChunkPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/process/transcribe': {
        post: {
            req: TranscribeVideoApiProcessTranscribePostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/process/filter-subtitles': {
        post: {
            req: FilterSubtitlesApiProcessFilterSubtitlesPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/process/translate-subtitles': {
        post: {
            req: TranslateSubtitlesApiProcessTranslateSubtitlesPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/process/prepare-episode': {
        post: {
            req: PrepareEpisodeApiProcessPrepareEpisodePostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/process/full-pipeline': {
        post: {
            req: FullPipelineApiProcessFullPipelinePostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/process/progress/{task_id}': {
        get: {
            req: GetTaskProgressApiProcessProgressTaskIdGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/vocabulary/languages': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: LanguagesResponse;
            };
        };
    };
    '/api/vocabulary/stats': {
        get: {
            req: GetVocabularyStatsApiVocabularyStatsGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: VocabularyStats;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/vocabulary/library/{level}': {
        get: {
            req: GetVocabularyLevelApiVocabularyLibraryLevelGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/vocabulary/mark-known': {
        post: {
            req: MarkWordKnownApiVocabularyMarkKnownPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/vocabulary/library/bulk-mark': {
        post: {
            req: BulkMarkLevelApiVocabularyLibraryBulkMarkPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/vocabulary/test-data': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/api/vocabulary/blocking-words': {
        get: {
            req: GetBlockingWordsApiVocabularyBlockingWordsGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/profile': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: UserProfile;
            };
        };
    };
    '/api/profile/languages': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: {
                    [key: string]: {
                        [key: string]: (string);
                    };
                };
            };
        };
        put: {
            req: ProfileUpdateLanguagesApiProfileLanguagesPutData;
            res: {
                /**
                 * Successful Response
                 */
                200: {
                    [key: string]: unknown;
                };
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/profile/settings': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: UserSettings;
            };
        };
        put: {
            req: ProfileUpdateSettingsApiProfileSettingsPutData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserSettings;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/progress/user': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: UserProgress;
            };
        };
    };
    '/api/progress/update': {
        post: {
            req: ProgressUpdateUserApiProgressUpdatePostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/progress/daily': {
        get: {
            req: ProgressGetDailyApiProgressDailyGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<DailyProgress>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/game/start': {
        post: {
            req: GameStartSessionApiGameStartPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: GameSession;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/game/session/{session_id}': {
        get: {
            req: GameGetSessionApiGameSessionSessionIdGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: GameSession;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/game/answer': {
        post: {
            req: GameSubmitAnswerApiGameAnswerPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/game/sessions': {
        get: {
            req: GameGetUserSessionsApiGameSessionsGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<GameSession>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/srt/parse': {
        post: {
            req: ParseSrtContentApiSrtParsePostData;
            res: {
                /**
                 * Successful Response
                 */
                200: ParseSRTResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/srt/parse-file': {
        post: {
            req: ParseSrtFileApiSrtParseFilePostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/srt/convert-to-srt': {
        post: {
            req: ConvertToSrtApiSrtConvertToSrtPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/srt/validate': {
        get: {
            req: ValidateSrtContentApiSrtValidateGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
};
