// This file is auto-generated by @hey-api/openapi-ts

/**
 * AnswerRequest
 * Request model for submitting an answer
 */
export type AnswerRequest = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Answer
     */
    answer: string;
};

/**
 * AuthResponse
 */
export type AuthResponse = {
    /**
     * Token
     * JWT authentication token
     */
    token: string;
    /**
     * User information
     */
    user: UserResponse;
    /**
     * Expires At
     * Token expiration timestamp (ISO format)
     */
    expires_at: string;
};

/**
 * Body_upload_subtitle_api_videos_subtitle_upload_post
 */
export type BodyUploadSubtitleApiVideosSubtitleUploadPost = {
    /**
     * Subtitle File
     */
    subtitle_file: Blob | File;
};

/**
 * Body_upload_video_api_videos_upload__series__post
 */
export type BodyUploadVideoApiVideosUploadSeriesPost = {
    /**
     * Video File
     */
    video_file: Blob | File;
};

/**
 * Body_upload_video_generic_api_videos_upload_post
 */
export type BodyUploadVideoGenericApiVideosUploadPost = {
    /**
     * Video File
     */
    video_file: Blob | File;
};

/**
 * BulkMarkRequest
 */
export type BulkMarkRequest = {
    /**
     * Level
     * CEFR difficulty level to mark (A1, A2, B1, B2, C1, C2)
     */
    level: string;
    /**
     * Known
     * Whether to mark all words in the level as known (true) or unknown (false)
     */
    known: boolean;
};

/**
 * ChunkProcessingRequest
 */
export type ChunkProcessingRequest = {
    /**
     * Video Path
     * Path to the video file to process
     */
    video_path: string;
    /**
     * Start Time
     * Start time of the chunk in seconds
     */
    start_time: number;
    /**
     * End Time
     * End time of the chunk in seconds
     */
    end_time: number;
};

/**
 * DailyProgress
 * Daily progress model
 */
export type DailyProgress = {
    /**
     * Date
     */
    date: string;
    /**
     * Videos Watched
     */
    videos_watched?: number;
    /**
     * Watch Time
     */
    watch_time?: number;
    /**
     * Vocabulary Learned
     */
    vocabulary_learned?: number;
    /**
     * Goals Completed
     */
    goals_completed?: number;
    /**
     * Experience Gained
     */
    experience_gained?: number;
};

/**
 * FilterRequest
 */
export type FilterRequest = {
    /**
     * Video Path
     * Path to the video file to filter subtitles for
     */
    video_path: string;
};

/**
 * FrontendLogEntry
 */
export type FrontendLogEntry = {
    /**
     * Timestamp
     */
    timestamp: string;
    /**
     * Level
     */
    level: string;
    /**
     * Category
     */
    category: string;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: unknown;
    /**
     * Error
     */
    error?: string;
    /**
     * Stack
     */
    stack?: string;
    /**
     * Url
     */
    url?: string;
    /**
     * Useragent
     */
    userAgent?: string;
    /**
     * Userid
     */
    userId?: string;
};

/**
 * FullPipelineRequest
 */
export type FullPipelineRequest = {
    /**
     * Video Path
     * Path to the video file to process
     */
    video_path: string;
    /**
     * Source Lang
     * Source language code (e.g., 'de', 'en-US')
     */
    source_lang?: string;
    /**
     * Target Lang
     * Target language code (e.g., 'en', 'de-DE')
     */
    target_lang?: string;
};

/**
 * GameSession
 * Game session model
 */
export type GameSession = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Game Type
     */
    game_type: string;
    /**
     * Difficulty
     */
    difficulty?: string;
    /**
     * Video Id
     */
    video_id?: string | null;
    /**
     * Start Time
     */
    start_time: string;
    /**
     * End Time
     */
    end_time?: string | null;
    /**
     * Status
     */
    status?: string;
    /**
     * Score
     */
    score?: number;
    /**
     * Max Score
     */
    max_score?: number;
    /**
     * Questions Answered
     */
    questions_answered?: number;
    /**
     * Correct Answers
     */
    correct_answers?: number;
    /**
     * Current Question
     */
    current_question?: number;
    /**
     * Total Questions
     */
    total_questions?: number;
    /**
     * Session Data
     */
    session_data?: {
        [key: string]: unknown;
    };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LanguagePreferences
 * Language preference update model
 */
export type LanguagePreferences = {
    /**
     * Native Language
     */
    native_language: string;
    /**
     * Target Language
     */
    target_language: string;
};

/**
 * LogBatch
 */
export type LogBatch = {
    /**
     * Entries
     */
    entries: Array<LogEntry>;
    /**
     * Client Id
     */
    client_id?: string;
};

/**
 * LogEntry
 */
export type LogEntry = {
    /**
     * Timestamp
     */
    timestamp: string;
    /**
     * Level
     */
    level: string;
    /**
     * Component
     */
    component: string;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: string;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Username
     * Username for authentication
     */
    username: string;
    /**
     * Password
     * Password for authentication
     */
    password: string;
};

/**
 * MarkKnownRequest
 */
export type MarkKnownRequest = {
    /**
     * Word
     * The word to mark as known/unknown
     */
    word: string;
    /**
     * Known
     * Whether to mark the word as known (true) or unknown (false)
     */
    known: boolean;
};

/**
 * ProcessingStatus
 */
export type ProcessingStatus = {
    /**
     * Status
     */
    status: string;
    /**
     * Progress
     */
    progress: number;
    /**
     * Current Step
     */
    current_step: string;
    /**
     * Message
     */
    message?: string;
    /**
     * Subtitle Path
     */
    subtitle_path?: string;
};

/**
 * RegisterRequest
 */
export type RegisterRequest = {
    /**
     * Username
     * Username must be 3-50 characters, alphanumeric with underscores and hyphens only
     */
    username: string;
    /**
     * Password
     * Password must be at least 8 characters long
     */
    password: string;
};

/**
 * StartGameRequest
 * Request model for starting a game session
 */
export type StartGameRequest = {
    /**
     * Game Type
     */
    game_type: string;
    /**
     * Difficulty
     */
    difficulty?: string;
    /**
     * Video Id
     */
    video_id?: string | null;
    /**
     * Total Questions
     */
    total_questions?: number;
};

/**
 * TranscribeRequest
 */
export type TranscribeRequest = {
    /**
     * Video Path
     * Path to the video file to transcribe
     */
    video_path: string;
};

/**
 * TranslateRequest
 */
export type TranslateRequest = {
    /**
     * Video Path
     * Path to the video file to translate subtitles for
     */
    video_path: string;
    /**
     * Source Lang
     * Source language code (e.g., 'de', 'en-US')
     */
    source_lang: string;
    /**
     * Target Lang
     * Target language code (e.g., 'en', 'de-DE')
     */
    target_lang: string;
};

/**
 * UserProfile
 * User profile response model
 */
export type UserProfile = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Is Admin
     */
    is_admin: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Last Login
     */
    last_login?: string;
    /**
     * Native Language
     */
    native_language: {
        [key: string]: string;
    };
    /**
     * Target Language
     */
    target_language: {
        [key: string]: string;
    };
};

/**
 * UserProgress
 * User progress model
 */
export type UserProgress = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Total Videos Watched
     */
    total_videos_watched?: number;
    /**
     * Total Watch Time
     */
    total_watch_time?: number;
    /**
     * Vocabulary Learned
     */
    vocabulary_learned?: number;
    /**
     * Current Streak
     */
    current_streak?: number;
    /**
     * Longest Streak
     */
    longest_streak?: number;
    /**
     * Level
     */
    level?: string;
    /**
     * Experience Points
     */
    experience_points?: number;
    /**
     * Daily Goals Completed
     */
    daily_goals_completed?: number;
    /**
     * Weekly Goals Completed
     */
    weekly_goals_completed?: number;
    /**
     * Last Activity
     */
    last_activity?: string | null;
    /**
     * Achievements
     */
    achievements?: Array<string>;
    /**
     * Learning Stats
     */
    learning_stats?: {
        [key: string]: unknown;
    };
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     * Unique user identifier
     */
    id: number;
    /**
     * Username
     * Username
     */
    username: string;
    /**
     * Is Admin
     * Whether user has admin privileges
     */
    is_admin: boolean;
    /**
     * Is Active
     * Whether user account is active
     */
    is_active: boolean;
    /**
     * Created At
     * Account creation timestamp (ISO format)
     */
    created_at: string;
    /**
     * Last Login
     * Last login timestamp (ISO format)
     */
    last_login?: string | null;
};

/**
 * UserSettings
 * User settings model
 */
export type UserSettings = {
    /**
     * Theme
     */
    theme?: string | null;
    /**
     * Notifications Enabled
     */
    notifications_enabled?: boolean | null;
    /**
     * Auto Play
     */
    auto_play?: boolean | null;
    /**
     * Subtitle Size
     */
    subtitle_size?: string | null;
    /**
     * Playback Speed
     */
    playback_speed?: number | null;
    /**
     * Vocabulary Difficulty
     */
    vocabulary_difficulty?: string | null;
    /**
     * Daily Goal
     */
    daily_goal?: number | null;
    language_preferences?: LanguagePreferences | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VocabularyStats
 */
export type VocabularyStats = {
    /**
     * Levels
     * Statistics by CEFR level with total and known counts
     */
    levels: {
        [key: string]: {
            [key: string]: number;
        };
    };
    /**
     * Total Words
     * Total number of vocabulary words across all levels
     */
    total_words: number;
    /**
     * Total Known
     * Total number of known words across all levels
     */
    total_known: number;
};

/**
 * VocabularyWord
 */
export type VocabularyWord = {
    /**
     * Word
     * The vocabulary word
     */
    word: string;
    /**
     * Definition
     * Definition of the word
     */
    definition?: string | null;
    /**
     * Difficulty Level
     * CEFR difficulty level (A1, A2, B1, B2, C1, C2)
     */
    difficulty_level: string;
    /**
     * Known
     * Whether the user knows this word
     */
    known?: boolean;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TestEndpointTestGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/test';
};

export type TestEndpointTestGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TestPrefixEndpointApiAuthTestPrefixGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/test-prefix';
};

export type TestPrefixEndpointApiAuthTestPrefixGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RegisterApiAuthRegisterPostData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterApiAuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterApiAuthRegisterPostError = RegisterApiAuthRegisterPostErrors[keyof RegisterApiAuthRegisterPostErrors];

export type RegisterApiAuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type RegisterApiAuthRegisterPostResponse = RegisterApiAuthRegisterPostResponses[keyof RegisterApiAuthRegisterPostResponses];

export type LoginApiAuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginApiAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiAuthLoginPostError = LoginApiAuthLoginPostErrors[keyof LoginApiAuthLoginPostErrors];

export type LoginApiAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: AuthResponse;
};

export type LoginApiAuthLoginPostResponse = LoginApiAuthLoginPostResponses[keyof LoginApiAuthLoginPostResponses];

export type LogoutApiAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutApiAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCurrentUserInfoApiAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetCurrentUserInfoApiAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetCurrentUserInfoApiAuthMeGetResponse = GetCurrentUserInfoApiAuthMeGetResponses[keyof GetCurrentUserInfoApiAuthMeGetResponses];

export type GetAvailableVideosApiVideosGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/videos';
};

export type GetAvailableVideosApiVideosGetResponses = {
    /**
     * Response Get Available Videos Api Videos Get
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetAvailableVideosApiVideosGetResponse = GetAvailableVideosApiVideosGetResponses[keyof GetAvailableVideosApiVideosGetResponses];

export type GetSubtitlesApiVideosSubtitlesSubtitlePathGetData = {
    body?: never;
    path: {
        /**
         * Subtitle Path
         */
        subtitle_path: string;
    };
    query?: never;
    url: '/api/videos/subtitles/{subtitle_path}';
};

export type GetSubtitlesApiVideosSubtitlesSubtitlePathGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSubtitlesApiVideosSubtitlesSubtitlePathGetError = GetSubtitlesApiVideosSubtitlesSubtitlePathGetErrors[keyof GetSubtitlesApiVideosSubtitlesSubtitlePathGetErrors];

export type GetSubtitlesApiVideosSubtitlesSubtitlePathGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StreamVideoApiVideosSeriesEpisodeGetData = {
    body?: never;
    path: {
        /**
         * Series
         */
        series: string;
        /**
         * Episode
         */
        episode: string;
    };
    query?: never;
    url: '/api/videos/{series}/{episode}';
};

export type StreamVideoApiVideosSeriesEpisodeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamVideoApiVideosSeriesEpisodeGetError = StreamVideoApiVideosSeriesEpisodeGetErrors[keyof StreamVideoApiVideosSeriesEpisodeGetErrors];

export type StreamVideoApiVideosSeriesEpisodeGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadSubtitleApiVideosSubtitleUploadPostData = {
    body: BodyUploadSubtitleApiVideosSubtitleUploadPost;
    path?: never;
    query: {
        /**
         * Video Path
         */
        video_path: string;
    };
    url: '/api/videos/subtitle/upload';
};

export type UploadSubtitleApiVideosSubtitleUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadSubtitleApiVideosSubtitleUploadPostError = UploadSubtitleApiVideosSubtitleUploadPostErrors[keyof UploadSubtitleApiVideosSubtitleUploadPostErrors];

export type UploadSubtitleApiVideosSubtitleUploadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ScanVideosApiVideosScanPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/videos/scan';
};

export type ScanVideosApiVideosScanPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUserVideosApiVideosUserGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/videos/user';
};

export type GetUserVideosApiVideosUserGetResponses = {
    /**
     * Response Get User Videos Api Videos User Get
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetUserVideosApiVideosUserGetResponse = GetUserVideosApiVideosUserGetResponses[keyof GetUserVideosApiVideosUserGetResponses];

export type GetVideoVocabularyApiVideosVideoIdVocabularyGetData = {
    body?: never;
    path: {
        /**
         * Video Id
         */
        video_id: string;
    };
    query?: never;
    url: '/api/videos/{video_id}/vocabulary';
};

export type GetVideoVocabularyApiVideosVideoIdVocabularyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVideoVocabularyApiVideosVideoIdVocabularyGetError = GetVideoVocabularyApiVideosVideoIdVocabularyGetErrors[keyof GetVideoVocabularyApiVideosVideoIdVocabularyGetErrors];

export type GetVideoVocabularyApiVideosVideoIdVocabularyGetResponses = {
    /**
     * Response Get Video Vocabulary Api Videos  Video Id  Vocabulary Get
     * Successful Response
     */
    200: Array<VocabularyWord>;
};

export type GetVideoVocabularyApiVideosVideoIdVocabularyGetResponse = GetVideoVocabularyApiVideosVideoIdVocabularyGetResponses[keyof GetVideoVocabularyApiVideosVideoIdVocabularyGetResponses];

export type GetVideoStatusApiVideosVideoIdStatusGetData = {
    body?: never;
    path: {
        /**
         * Video Id
         */
        video_id: string;
    };
    query?: never;
    url: '/api/videos/{video_id}/status';
};

export type GetVideoStatusApiVideosVideoIdStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVideoStatusApiVideosVideoIdStatusGetError = GetVideoStatusApiVideosVideoIdStatusGetErrors[keyof GetVideoStatusApiVideosVideoIdStatusGetErrors];

export type GetVideoStatusApiVideosVideoIdStatusGetResponses = {
    /**
     * Successful Response
     */
    200: ProcessingStatus;
};

export type GetVideoStatusApiVideosVideoIdStatusGetResponse = GetVideoStatusApiVideosVideoIdStatusGetResponses[keyof GetVideoStatusApiVideosVideoIdStatusGetResponses];

export type UploadVideoGenericApiVideosUploadPostData = {
    body: BodyUploadVideoGenericApiVideosUploadPost;
    path?: never;
    query?: {
        /**
         * Series
         */
        series?: string;
    };
    url: '/api/videos/upload';
};

export type UploadVideoGenericApiVideosUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadVideoGenericApiVideosUploadPostError = UploadVideoGenericApiVideosUploadPostErrors[keyof UploadVideoGenericApiVideosUploadPostErrors];

export type UploadVideoGenericApiVideosUploadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadVideoApiVideosUploadSeriesPostData = {
    body: BodyUploadVideoApiVideosUploadSeriesPost;
    path: {
        /**
         * Series
         */
        series: string;
    };
    query?: never;
    url: '/api/videos/upload/{series}';
};

export type UploadVideoApiVideosUploadSeriesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadVideoApiVideosUploadSeriesPostError = UploadVideoApiVideosUploadSeriesPostErrors[keyof UploadVideoApiVideosUploadSeriesPostErrors];

export type UploadVideoApiVideosUploadSeriesPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProcessChunkApiProcessChunkPostData = {
    body: ChunkProcessingRequest;
    path?: never;
    query?: never;
    url: '/api/process/chunk';
};

export type ProcessChunkApiProcessChunkPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProcessChunkApiProcessChunkPostError = ProcessChunkApiProcessChunkPostErrors[keyof ProcessChunkApiProcessChunkPostErrors];

export type ProcessChunkApiProcessChunkPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TranscribeVideoApiProcessTranscribePostData = {
    body: TranscribeRequest;
    path?: never;
    query?: never;
    url: '/api/process/transcribe';
};

export type TranscribeVideoApiProcessTranscribePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TranscribeVideoApiProcessTranscribePostError = TranscribeVideoApiProcessTranscribePostErrors[keyof TranscribeVideoApiProcessTranscribePostErrors];

export type TranscribeVideoApiProcessTranscribePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FilterSubtitlesApiProcessFilterSubtitlesPostData = {
    body: FilterRequest;
    path?: never;
    query?: never;
    url: '/api/process/filter-subtitles';
};

export type FilterSubtitlesApiProcessFilterSubtitlesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FilterSubtitlesApiProcessFilterSubtitlesPostError = FilterSubtitlesApiProcessFilterSubtitlesPostErrors[keyof FilterSubtitlesApiProcessFilterSubtitlesPostErrors];

export type FilterSubtitlesApiProcessFilterSubtitlesPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TranslateSubtitlesApiProcessTranslateSubtitlesPostData = {
    body: TranslateRequest;
    path?: never;
    query?: never;
    url: '/api/process/translate-subtitles';
};

export type TranslateSubtitlesApiProcessTranslateSubtitlesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TranslateSubtitlesApiProcessTranslateSubtitlesPostError = TranslateSubtitlesApiProcessTranslateSubtitlesPostErrors[keyof TranslateSubtitlesApiProcessTranslateSubtitlesPostErrors];

export type TranslateSubtitlesApiProcessTranslateSubtitlesPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PrepareEpisodeForLearningApiProcessPrepareEpisodePostData = {
    body: TranscribeRequest;
    path?: never;
    query?: never;
    url: '/api/process/prepare-episode';
};

export type PrepareEpisodeForLearningApiProcessPrepareEpisodePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PrepareEpisodeForLearningApiProcessPrepareEpisodePostError = PrepareEpisodeForLearningApiProcessPrepareEpisodePostErrors[keyof PrepareEpisodeForLearningApiProcessPrepareEpisodePostErrors];

export type PrepareEpisodeForLearningApiProcessPrepareEpisodePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FullPipelineApiProcessFullPipelinePostData = {
    body: FullPipelineRequest;
    path?: never;
    query?: never;
    url: '/api/process/full-pipeline';
};

export type FullPipelineApiProcessFullPipelinePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FullPipelineApiProcessFullPipelinePostError = FullPipelineApiProcessFullPipelinePostErrors[keyof FullPipelineApiProcessFullPipelinePostErrors];

export type FullPipelineApiProcessFullPipelinePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTaskProgressApiProcessProgressTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/process/progress/{task_id}';
};

export type GetTaskProgressApiProcessProgressTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskProgressApiProcessProgressTaskIdGetError = GetTaskProgressApiProcessProgressTaskIdGetErrors[keyof GetTaskProgressApiProcessProgressTaskIdGetErrors];

export type GetTaskProgressApiProcessProgressTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetVocabularyStatsEndpointApiVocabularyStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/vocabulary/stats';
};

export type GetVocabularyStatsEndpointApiVocabularyStatsGetResponses = {
    /**
     * Successful Response
     */
    200: VocabularyStats;
};

export type GetVocabularyStatsEndpointApiVocabularyStatsGetResponse = GetVocabularyStatsEndpointApiVocabularyStatsGetResponses[keyof GetVocabularyStatsEndpointApiVocabularyStatsGetResponses];

export type GetBlockingWordsApiVocabularyBlockingWordsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Video Path
         */
        video_path: string;
        /**
         * Segment Start
         */
        segment_start?: number;
        /**
         * Segment Duration
         */
        segment_duration?: number;
    };
    url: '/api/vocabulary/blocking-words';
};

export type GetBlockingWordsApiVocabularyBlockingWordsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBlockingWordsApiVocabularyBlockingWordsGetError = GetBlockingWordsApiVocabularyBlockingWordsGetErrors[keyof GetBlockingWordsApiVocabularyBlockingWordsGetErrors];

export type GetBlockingWordsApiVocabularyBlockingWordsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type MarkWordAsKnownApiVocabularyMarkKnownPostData = {
    body: MarkKnownRequest;
    path?: never;
    query?: never;
    url: '/api/vocabulary/mark-known';
};

export type MarkWordAsKnownApiVocabularyMarkKnownPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MarkWordAsKnownApiVocabularyMarkKnownPostError = MarkWordAsKnownApiVocabularyMarkKnownPostErrors[keyof MarkWordAsKnownApiVocabularyMarkKnownPostErrors];

export type MarkWordAsKnownApiVocabularyMarkKnownPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PreloadVocabularyApiVocabularyPreloadPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/vocabulary/preload';
};

export type PreloadVocabularyApiVocabularyPreloadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetVocabularyStatsApiVocabularyLibraryStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/vocabulary/library/stats';
};

export type GetVocabularyStatsApiVocabularyLibraryStatsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetVocabularyLevelApiVocabularyLibraryLevelGetData = {
    body?: never;
    path: {
        /**
         * Level
         */
        level: string;
    };
    query?: never;
    url: '/api/vocabulary/library/{level}';
};

export type GetVocabularyLevelApiVocabularyLibraryLevelGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVocabularyLevelApiVocabularyLibraryLevelGetError = GetVocabularyLevelApiVocabularyLibraryLevelGetErrors[keyof GetVocabularyLevelApiVocabularyLibraryLevelGetErrors];

export type GetVocabularyLevelApiVocabularyLibraryLevelGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BulkMarkLevelKnownApiVocabularyLibraryBulkMarkPostData = {
    body: BulkMarkRequest;
    path?: never;
    query?: never;
    url: '/api/vocabulary/library/bulk-mark';
};

export type BulkMarkLevelKnownApiVocabularyLibraryBulkMarkPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BulkMarkLevelKnownApiVocabularyLibraryBulkMarkPostError = BulkMarkLevelKnownApiVocabularyLibraryBulkMarkPostErrors[keyof BulkMarkLevelKnownApiVocabularyLibraryBulkMarkPostErrors];

export type BulkMarkLevelKnownApiVocabularyLibraryBulkMarkPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetProfileApiProfileGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/profile';
};

export type GetProfileApiProfileGetResponses = {
    /**
     * Successful Response
     */
    200: UserProfile;
};

export type GetProfileApiProfileGetResponse = GetProfileApiProfileGetResponses[keyof GetProfileApiProfileGetResponses];

export type GetSupportedLanguagesApiProfileLanguagesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/profile/languages';
};

export type GetSupportedLanguagesApiProfileLanguagesGetResponses = {
    /**
     * Response Get Supported Languages Api Profile Languages Get
     * Successful Response
     */
    200: {
        [key: string]: {
            [key: string]: string;
        };
    };
};

export type GetSupportedLanguagesApiProfileLanguagesGetResponse = GetSupportedLanguagesApiProfileLanguagesGetResponses[keyof GetSupportedLanguagesApiProfileLanguagesGetResponses];

export type UpdateLanguagePreferencesApiProfileLanguagesPutData = {
    body: LanguagePreferences;
    path?: never;
    query?: never;
    url: '/api/profile/languages';
};

export type UpdateLanguagePreferencesApiProfileLanguagesPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateLanguagePreferencesApiProfileLanguagesPutError = UpdateLanguagePreferencesApiProfileLanguagesPutErrors[keyof UpdateLanguagePreferencesApiProfileLanguagesPutErrors];

export type UpdateLanguagePreferencesApiProfileLanguagesPutResponses = {
    /**
     * Response Update Language Preferences Api Profile Languages Put
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UpdateLanguagePreferencesApiProfileLanguagesPutResponse = UpdateLanguagePreferencesApiProfileLanguagesPutResponses[keyof UpdateLanguagePreferencesApiProfileLanguagesPutResponses];

export type GetUserSettingsApiProfileSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/profile/settings';
};

export type GetUserSettingsApiProfileSettingsGetResponses = {
    /**
     * Successful Response
     */
    200: UserSettings;
};

export type GetUserSettingsApiProfileSettingsGetResponse = GetUserSettingsApiProfileSettingsGetResponses[keyof GetUserSettingsApiProfileSettingsGetResponses];

export type UpdateUserSettingsApiProfileSettingsPutData = {
    body: UserSettings;
    path?: never;
    query?: never;
    url: '/api/profile/settings';
};

export type UpdateUserSettingsApiProfileSettingsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserSettingsApiProfileSettingsPutError = UpdateUserSettingsApiProfileSettingsPutErrors[keyof UpdateUserSettingsApiProfileSettingsPutErrors];

export type UpdateUserSettingsApiProfileSettingsPutResponses = {
    /**
     * Successful Response
     */
    200: UserSettings;
};

export type UpdateUserSettingsApiProfileSettingsPutResponse = UpdateUserSettingsApiProfileSettingsPutResponses[keyof UpdateUserSettingsApiProfileSettingsPutResponses];

export type ReceiveFrontendLogsApiLogsFrontendPostData = {
    body: LogBatch;
    path?: never;
    query?: never;
    url: '/api/logs/frontend';
};

export type ReceiveFrontendLogsApiLogsFrontendPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReceiveFrontendLogsApiLogsFrontendPostError = ReceiveFrontendLogsApiLogsFrontendPostErrors[keyof ReceiveFrontendLogsApiLogsFrontendPostErrors];

export type ReceiveFrontendLogsApiLogsFrontendPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListLogFilesApiLogsListGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/logs/list';
};

export type ListLogFilesApiLogsListGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DownloadLogFileApiLogsDownloadFilenameGetData = {
    body?: never;
    path: {
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/api/logs/download/{filename}';
};

export type DownloadLogFileApiLogsDownloadFilenameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadLogFileApiLogsDownloadFilenameGetError = DownloadLogFileApiLogsDownloadFilenameGetErrors[keyof DownloadLogFileApiLogsDownloadFilenameGetErrors];

export type DownloadLogFileApiLogsDownloadFilenameGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUserProgressApiProgressUserGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/progress/user';
};

export type GetUserProgressApiProgressUserGetResponses = {
    /**
     * Successful Response
     */
    200: UserProgress;
};

export type GetUserProgressApiProgressUserGetResponse = GetUserProgressApiProgressUserGetResponses[keyof GetUserProgressApiProgressUserGetResponses];

export type UpdateUserProgressApiProgressUpdatePostData = {
    /**
     * Progress Update
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/progress/update';
};

export type UpdateUserProgressApiProgressUpdatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserProgressApiProgressUpdatePostError = UpdateUserProgressApiProgressUpdatePostErrors[keyof UpdateUserProgressApiProgressUpdatePostErrors];

export type UpdateUserProgressApiProgressUpdatePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetDailyProgressApiProgressDailyGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Days
         */
        days?: number;
    };
    url: '/api/progress/daily';
};

export type GetDailyProgressApiProgressDailyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDailyProgressApiProgressDailyGetError = GetDailyProgressApiProgressDailyGetErrors[keyof GetDailyProgressApiProgressDailyGetErrors];

export type GetDailyProgressApiProgressDailyGetResponses = {
    /**
     * Response Get Daily Progress Api Progress Daily Get
     * Successful Response
     */
    200: Array<DailyProgress>;
};

export type GetDailyProgressApiProgressDailyGetResponse = GetDailyProgressApiProgressDailyGetResponses[keyof GetDailyProgressApiProgressDailyGetResponses];

export type StartGameSessionApiGameStartPostData = {
    body: StartGameRequest;
    path?: never;
    query?: never;
    url: '/api/game/start';
};

export type StartGameSessionApiGameStartPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartGameSessionApiGameStartPostError = StartGameSessionApiGameStartPostErrors[keyof StartGameSessionApiGameStartPostErrors];

export type StartGameSessionApiGameStartPostResponses = {
    /**
     * Successful Response
     */
    200: GameSession;
};

export type StartGameSessionApiGameStartPostResponse = StartGameSessionApiGameStartPostResponses[keyof StartGameSessionApiGameStartPostResponses];

export type GetGameSessionApiGameSessionSessionIdGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/game/session/{session_id}';
};

export type GetGameSessionApiGameSessionSessionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGameSessionApiGameSessionSessionIdGetError = GetGameSessionApiGameSessionSessionIdGetErrors[keyof GetGameSessionApiGameSessionSessionIdGetErrors];

export type GetGameSessionApiGameSessionSessionIdGetResponses = {
    /**
     * Successful Response
     */
    200: GameSession;
};

export type GetGameSessionApiGameSessionSessionIdGetResponse = GetGameSessionApiGameSessionSessionIdGetResponses[keyof GetGameSessionApiGameSessionSessionIdGetResponses];

export type SubmitAnswerApiGameAnswerPostData = {
    body: AnswerRequest;
    path?: never;
    query?: never;
    url: '/api/game/answer';
};

export type SubmitAnswerApiGameAnswerPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitAnswerApiGameAnswerPostError = SubmitAnswerApiGameAnswerPostErrors[keyof SubmitAnswerApiGameAnswerPostErrors];

export type SubmitAnswerApiGameAnswerPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUserGameSessionsApiGameSessionsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/game/sessions';
};

export type GetUserGameSessionsApiGameSessionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserGameSessionsApiGameSessionsGetError = GetUserGameSessionsApiGameSessionsGetErrors[keyof GetUserGameSessionsApiGameSessionsGetErrors];

export type GetUserGameSessionsApiGameSessionsGetResponses = {
    /**
     * Response Get User Game Sessions Api Game Sessions Get
     * Successful Response
     */
    200: Array<GameSession>;
};

export type GetUserGameSessionsApiGameSessionsGetResponse = GetUserGameSessionsApiGameSessionsGetResponses[keyof GetUserGameSessionsApiGameSessionsGetResponses];

export type ReceiveFrontendLogApiDebugFrontendLogsPostData = {
    body: FrontendLogEntry;
    path?: never;
    query?: never;
    url: '/api/debug/frontend-logs';
};

export type ReceiveFrontendLogApiDebugFrontendLogsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReceiveFrontendLogApiDebugFrontendLogsPostError = ReceiveFrontendLogApiDebugFrontendLogsPostErrors[keyof ReceiveFrontendLogApiDebugFrontendLogsPostErrors];

export type ReceiveFrontendLogApiDebugFrontendLogsPostResponses = {
    /**
     * Response Receive Frontend Log Api Debug Frontend Logs Post
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ReceiveFrontendLogApiDebugFrontendLogsPostResponse = ReceiveFrontendLogApiDebugFrontendLogsPostResponses[keyof ReceiveFrontendLogApiDebugFrontendLogsPostResponses];

export type DebugHealthApiDebugHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/debug/health';
};

export type DebugHealthApiDebugHealthGetResponses = {
    /**
     * Response Debug Health Api Debug Health Get
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type DebugHealthApiDebugHealthGetResponse = DebugHealthApiDebugHealthGetResponses[keyof DebugHealthApiDebugHealthGetResponses];

export type TestMinimalPostApiDebugTestMinimalPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/debug/test-minimal';
};

export type TestMinimalPostApiDebugTestMinimalPostResponses = {
    /**
     * Response Test Minimal Post Api Debug Test Minimal Post
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type TestMinimalPostApiDebugTestMinimalPostResponse = TestMinimalPostApiDebugTestMinimalPostResponses[keyof TestMinimalPostApiDebugTestMinimalPostResponses];

export type TestPostWithDataApiDebugTestWithDataPostData = {
    /**
     * Data
     */
    body?: {
        [key: string]: unknown;
    } | null;
    path?: never;
    query?: never;
    url: '/api/debug/test-with-data';
};

export type TestPostWithDataApiDebugTestWithDataPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestPostWithDataApiDebugTestWithDataPostError = TestPostWithDataApiDebugTestWithDataPostErrors[keyof TestPostWithDataApiDebugTestWithDataPostErrors];

export type TestPostWithDataApiDebugTestWithDataPostResponses = {
    /**
     * Response Test Post With Data Api Debug Test With Data Post
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TestPostWithDataApiDebugTestWithDataPostResponse = TestPostWithDataApiDebugTestWithDataPostResponses[keyof TestPostWithDataApiDebugTestWithDataPostResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};
