// This file is auto-generated by @hey-api/openapi-ts

/**
 * AnswerRequest
 * Request model for submitting an answer
 */
export type AnswerRequest = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Answer
     */
    answer: string;
};

/**
 * BearerResponse
 */
export type BearerResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * Body_auth_jwt_bearer_login_api_auth_login_post
 */
export type BodyAuthJwtBearerLoginApiAuthLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_parse_srt_file_api_srt_parse_file_post
 */
export type BodyParseSrtFileApiSrtParseFilePost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_subtitle_api_videos_subtitle_upload_post
 */
export type BodyUploadSubtitleApiVideosSubtitleUploadPost = {
    /**
     * Subtitle File
     */
    subtitle_file: Blob | File;
};

/**
 * Body_upload_video_generic_api_videos_upload_post
 */
export type BodyUploadVideoGenericApiVideosUploadPost = {
    /**
     * Video File
     */
    video_file: Blob | File;
};

/**
 * Body_upload_video_to_series_api_videos_upload__series__post
 */
export type BodyUploadVideoToSeriesApiVideosUploadSeriesPost = {
    /**
     * Video File
     */
    video_file: Blob | File;
};

/**
 * BulkMarkRequest
 */
export type BulkMarkRequest = {
    /**
     * Level
     * CEFR difficulty level to mark (A1, A2, B1, B2, C1, C2)
     */
    level: string;
    /**
     * Known
     * Whether to mark all words in the level as known (true) or unknown (false)
     */
    known: boolean;
};

/**
 * ChunkProcessingRequest
 */
export type ChunkProcessingRequest = {
    /**
     * Video Path
     * Path to the video file to process
     */
    video_path: string;
    /**
     * Start Time
     * Start time of the chunk in seconds
     */
    start_time: number;
    /**
     * End Time
     * End time of the chunk in seconds
     */
    end_time: number;
};

/**
 * ConvertToSRTRequest
 * Request model for converting segments to SRT format.
 */
export type ConvertToSrtRequest = {
    /**
     * Segments
     */
    segments: Array<SrtSegmentResponse>;
};

/**
 * DailyProgress
 * Daily progress model
 */
export type DailyProgress = {
    /**
     * Date
     */
    date: string;
    /**
     * Videos Watched
     */
    videos_watched?: number;
    /**
     * Watch Time
     */
    watch_time?: number;
    /**
     * Vocabulary Learned
     */
    vocabulary_learned?: number;
    /**
     * Goals Completed
     */
    goals_completed?: number;
    /**
     * Experience Gained
     */
    experience_gained?: number;
};

/**
 * ErrorModel
 */
export type ErrorModel = {
    /**
     * Detail
     */
    detail: string | {
        [key: string]: string;
    };
};

/**
 * FilterRequest
 */
export type FilterRequest = {
    /**
     * Video Path
     * Path to the video file to filter subtitles for
     */
    video_path: string;
};

/**
 * FullPipelineRequest
 */
export type FullPipelineRequest = {
    /**
     * Video Path
     * Path to the video file to process
     */
    video_path: string;
    /**
     * Source Lang
     * Source language code (e.g., 'de', 'en-US')
     */
    source_lang?: string;
    /**
     * Target Lang
     * Target language code (e.g., 'en', 'de-DE')
     */
    target_lang?: string;
};

/**
 * GameSession
 * Game session model
 */
export type GameSession = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Game Type
     */
    game_type: string;
    /**
     * Difficulty
     */
    difficulty?: string;
    /**
     * Video Id
     */
    video_id?: string | null;
    /**
     * Start Time
     */
    start_time: string;
    /**
     * End Time
     */
    end_time?: string | null;
    /**
     * Status
     */
    status?: string;
    /**
     * Score
     */
    score?: number;
    /**
     * Max Score
     */
    max_score?: number;
    /**
     * Questions Answered
     */
    questions_answered?: number;
    /**
     * Correct Answers
     */
    correct_answers?: number;
    /**
     * Current Question
     */
    current_question?: number;
    /**
     * Total Questions
     */
    total_questions?: number;
    /**
     * Session Data
     */
    session_data?: {
        [key: string]: unknown;
    };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LanguagePreferences
 * Language preference update model
 */
export type LanguagePreferences = {
    /**
     * Native Language
     */
    native_language: string;
    /**
     * Target Language
     */
    target_language: string;
};

/**
 * LogBatch
 */
export type LogBatch = {
    /**
     * Entries
     */
    entries: Array<LogEntry>;
    /**
     * Client Id
     */
    client_id?: string;
};

/**
 * LogEntry
 */
export type LogEntry = {
    /**
     * Timestamp
     */
    timestamp: string;
    /**
     * Level
     */
    level: string;
    /**
     * Component
     */
    component: string;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: string;
};

/**
 * MarkKnownRequest
 */
export type MarkKnownRequest = {
    /**
     * Word
     * The word to mark as known/unknown
     */
    word: string;
    /**
     * Known
     * Whether to mark the word as known (true) or unknown (false)
     */
    known: boolean;
};

/**
 * ParseSRTRequest
 * Request model for parsing SRT content.
 */
export type ParseSrtRequest = {
    /**
     * Content
     */
    content: string;
};

/**
 * ParseSRTResponse
 * Response model for parsed SRT data.
 */
export type ParseSrtResponse = {
    /**
     * Segments
     */
    segments: Array<SrtSegmentResponse>;
    /**
     * Total Segments
     */
    total_segments: number;
    /**
     * Duration
     */
    duration: number;
};

/**
 * ProcessingStatus
 */
export type ProcessingStatus = {
    /**
     * Status
     */
    status: string;
    /**
     * Progress
     */
    progress: number;
    /**
     * Current Step
     */
    current_step: string;
    /**
     * Message
     */
    message?: string;
    /**
     * Subtitle Path
     */
    subtitle_path?: string;
};

/**
 * SRTSegmentResponse
 * Response model for SRT segment data.
 */
export type SrtSegmentResponse = {
    /**
     * Index
     */
    index: number;
    /**
     * Start Time
     */
    start_time: number;
    /**
     * End Time
     */
    end_time: number;
    /**
     * Text
     */
    text: string;
    /**
     * Original Text
     */
    original_text?: string;
    /**
     * Translation
     */
    translation?: string;
};

/**
 * StartGameRequest
 * Request model for starting a game session
 */
export type StartGameRequest = {
    /**
     * Game Type
     */
    game_type: string;
    /**
     * Difficulty
     */
    difficulty?: string;
    /**
     * Video Id
     */
    video_id?: string | null;
    /**
     * Total Questions
     */
    total_questions?: number;
};

/**
 * TranscribeRequest
 */
export type TranscribeRequest = {
    /**
     * Video Path
     * Path to the video file to transcribe
     */
    video_path: string;
};

/**
 * TranslateRequest
 */
export type TranslateRequest = {
    /**
     * Video Path
     * Path to the video file to translate subtitles for
     */
    video_path: string;
    /**
     * Source Lang
     * Source language code (e.g., 'de', 'en-US')
     */
    source_lang: string;
    /**
     * Target Lang
     * Target language code (e.g., 'en', 'de-DE')
     */
    target_lang: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
    /**
     * Username
     */
    username: string;
};

/**
 * UserProfile
 * User profile response model
 */
export type UserProfile = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Is Admin
     */
    is_admin: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Last Login
     */
    last_login?: string | null;
    /**
     * Native Language
     */
    native_language: {
        [key: string]: string;
    };
    /**
     * Target Language
     */
    target_language: {
        [key: string]: string;
    };
};

/**
 * UserProgress
 * User progress model
 */
export type UserProgress = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Total Videos Watched
     */
    total_videos_watched?: number;
    /**
     * Total Watch Time
     */
    total_watch_time?: number;
    /**
     * Vocabulary Learned
     */
    vocabulary_learned?: number;
    /**
     * Current Streak
     */
    current_streak?: number;
    /**
     * Longest Streak
     */
    longest_streak?: number;
    /**
     * Level
     */
    level?: string;
    /**
     * Experience Points
     */
    experience_points?: number;
    /**
     * Daily Goals Completed
     */
    daily_goals_completed?: number;
    /**
     * Weekly Goals Completed
     */
    weekly_goals_completed?: number;
    /**
     * Last Activity
     */
    last_activity?: string | null;
    /**
     * Achievements
     */
    achievements?: Array<string>;
    /**
     * Learning Stats
     */
    learning_stats?: {
        [key: string]: unknown;
    };
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
    /**
     * Is Verified
     */
    is_verified: boolean;
    /**
     * Username
     */
    username: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Last Login
     */
    last_login: string | null;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     * Unique user identifier (UUID)
     */
    id: string;
    /**
     * Username
     * Username
     */
    username: string;
    /**
     * Email
     * User email address
     */
    email: string;
    /**
     * Is Superuser
     * Whether user has superuser privileges
     */
    is_superuser: boolean;
    /**
     * Is Active
     * Whether user account is active
     */
    is_active: boolean;
    /**
     * Created At
     * Account creation timestamp (ISO format)
     */
    created_at: string;
    /**
     * Last Login
     * Last login timestamp (ISO format)
     */
    last_login?: string | null;
};

/**
 * UserSettings
 * User settings model
 */
export type UserSettings = {
    /**
     * Theme
     */
    theme?: string | null;
    /**
     * Notifications Enabled
     */
    notifications_enabled?: boolean | null;
    /**
     * Auto Play
     */
    auto_play?: boolean | null;
    /**
     * Subtitle Size
     */
    subtitle_size?: string | null;
    /**
     * Playback Speed
     */
    playback_speed?: number | null;
    /**
     * Vocabulary Difficulty
     */
    vocabulary_difficulty?: string | null;
    /**
     * Daily Goal
     */
    daily_goal?: number | null;
    language_preferences?: LanguagePreferences | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VideoInfo
 */
export type VideoInfo = {
    /**
     * Series
     * Name of the TV series
     */
    series: string;
    /**
     * Season
     * Season identifier (e.g., 'S01', 'Season 1')
     */
    season: string;
    /**
     * Episode
     * Episode identifier (e.g., 'E01', 'Episode 1')
     */
    episode: string;
    /**
     * Title
     * Episode title
     */
    title: string;
    /**
     * Path
     * File system path to the video file
     */
    path: string;
    /**
     * Has Subtitles
     * Whether subtitles are available for this video
     */
    has_subtitles: boolean;
    /**
     * Duration
     * Video duration in seconds
     */
    duration?: number | null;
};

/**
 * VocabularyStats
 */
export type VocabularyStats = {
    /**
     * Levels
     * Statistics by CEFR level with total and known counts
     */
    levels: {
        [key: string]: {
            [key: string]: number;
        };
    };
    /**
     * Total Words
     * Total number of vocabulary words across all levels
     */
    total_words: number;
    /**
     * Total Known
     * Total number of known words across all levels
     */
    total_known: number;
};

/**
 * VocabularyWord
 */
export type VocabularyWord = {
    /**
     * Word
     * The vocabulary word
     */
    word: string;
    /**
     * Definition
     * Definition of the word
     */
    definition?: string | null;
    /**
     * Difficulty Level
     * CEFR difficulty level (A1, A2, B1, B2, C1, C2)
     */
    difficulty_level: string;
    /**
     * Known
     * Whether the user knows this word
     */
    known?: boolean;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TestEndpointTestGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/test';
};

export type TestEndpointTestGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AuthJwtBearerLogoutApiAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type AuthJwtBearerLogoutApiAuthLogoutPostErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
};

export type AuthJwtBearerLogoutApiAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AuthJwtBearerLoginApiAuthLoginPostData = {
    body: BodyAuthJwtBearerLoginApiAuthLoginPost;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type AuthJwtBearerLoginApiAuthLoginPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthJwtBearerLoginApiAuthLoginPostError = AuthJwtBearerLoginApiAuthLoginPostErrors[keyof AuthJwtBearerLoginApiAuthLoginPostErrors];

export type AuthJwtBearerLoginApiAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: BearerResponse;
};

export type AuthJwtBearerLoginApiAuthLoginPostResponse = AuthJwtBearerLoginApiAuthLoginPostResponses[keyof AuthJwtBearerLoginApiAuthLoginPostResponses];

export type RegisterRegisterApiAuthRegisterPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterRegisterApiAuthRegisterPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterRegisterApiAuthRegisterPostError = RegisterRegisterApiAuthRegisterPostErrors[keyof RegisterRegisterApiAuthRegisterPostErrors];

export type RegisterRegisterApiAuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type RegisterRegisterApiAuthRegisterPostResponse = RegisterRegisterApiAuthRegisterPostResponses[keyof RegisterRegisterApiAuthRegisterPostResponses];

export type AuthTestPrefixApiAuthTestPrefixGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/test-prefix';
};

export type AuthTestPrefixApiAuthTestPrefixGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AuthGetCurrentUserApiAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type AuthGetCurrentUserApiAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type AuthGetCurrentUserApiAuthMeGetResponse = AuthGetCurrentUserApiAuthMeGetResponses[keyof AuthGetCurrentUserApiAuthMeGetResponses];

export type GetVideosApiVideosGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/videos';
};

export type GetVideosApiVideosGetResponses = {
    /**
     * Response Get Videos Api Videos Get
     * Successful Response
     */
    200: Array<VideoInfo>;
};

export type GetVideosApiVideosGetResponse = GetVideosApiVideosGetResponses[keyof GetVideosApiVideosGetResponses];

export type GetSubtitlesApiVideosSubtitlesSubtitlePathGetData = {
    body?: never;
    path: {
        /**
         * Subtitle Path
         */
        subtitle_path: string;
    };
    query?: never;
    url: '/api/videos/subtitles/{subtitle_path}';
};

export type GetSubtitlesApiVideosSubtitlesSubtitlePathGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSubtitlesApiVideosSubtitlesSubtitlePathGetError = GetSubtitlesApiVideosSubtitlesSubtitlePathGetErrors[keyof GetSubtitlesApiVideosSubtitlesSubtitlePathGetErrors];

export type GetSubtitlesApiVideosSubtitlesSubtitlePathGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StreamVideoApiVideosSeriesEpisodeGetData = {
    body?: never;
    path: {
        /**
         * Series
         */
        series: string;
        /**
         * Episode
         */
        episode: string;
    };
    query?: never;
    url: '/api/videos/{series}/{episode}';
};

export type StreamVideoApiVideosSeriesEpisodeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamVideoApiVideosSeriesEpisodeGetError = StreamVideoApiVideosSeriesEpisodeGetErrors[keyof StreamVideoApiVideosSeriesEpisodeGetErrors];

export type StreamVideoApiVideosSeriesEpisodeGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadSubtitleApiVideosSubtitleUploadPostData = {
    body: BodyUploadSubtitleApiVideosSubtitleUploadPost;
    path?: never;
    query: {
        /**
         * Video Path
         */
        video_path: string;
    };
    url: '/api/videos/subtitle/upload';
};

export type UploadSubtitleApiVideosSubtitleUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadSubtitleApiVideosSubtitleUploadPostError = UploadSubtitleApiVideosSubtitleUploadPostErrors[keyof UploadSubtitleApiVideosSubtitleUploadPostErrors];

export type UploadSubtitleApiVideosSubtitleUploadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ScanVideosApiVideosScanPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/videos/scan';
};

export type ScanVideosApiVideosScanPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUserVideosApiVideosUserGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/videos/user';
};

export type GetUserVideosApiVideosUserGetResponses = {
    /**
     * Response Get User Videos Api Videos User Get
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetUserVideosApiVideosUserGetResponse = GetUserVideosApiVideosUserGetResponses[keyof GetUserVideosApiVideosUserGetResponses];

export type GetVideoVocabularyApiVideosVideoIdVocabularyGetData = {
    body?: never;
    path: {
        /**
         * Video Id
         */
        video_id: string;
    };
    query?: never;
    url: '/api/videos/{video_id}/vocabulary';
};

export type GetVideoVocabularyApiVideosVideoIdVocabularyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVideoVocabularyApiVideosVideoIdVocabularyGetError = GetVideoVocabularyApiVideosVideoIdVocabularyGetErrors[keyof GetVideoVocabularyApiVideosVideoIdVocabularyGetErrors];

export type GetVideoVocabularyApiVideosVideoIdVocabularyGetResponses = {
    /**
     * Response Get Video Vocabulary Api Videos  Video Id  Vocabulary Get
     * Successful Response
     */
    200: Array<VocabularyWord>;
};

export type GetVideoVocabularyApiVideosVideoIdVocabularyGetResponse = GetVideoVocabularyApiVideosVideoIdVocabularyGetResponses[keyof GetVideoVocabularyApiVideosVideoIdVocabularyGetResponses];

export type GetVideoStatusApiVideosVideoIdStatusGetData = {
    body?: never;
    path: {
        /**
         * Video Id
         */
        video_id: string;
    };
    query?: never;
    url: '/api/videos/{video_id}/status';
};

export type GetVideoStatusApiVideosVideoIdStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVideoStatusApiVideosVideoIdStatusGetError = GetVideoStatusApiVideosVideoIdStatusGetErrors[keyof GetVideoStatusApiVideosVideoIdStatusGetErrors];

export type GetVideoStatusApiVideosVideoIdStatusGetResponses = {
    /**
     * Successful Response
     */
    200: ProcessingStatus;
};

export type GetVideoStatusApiVideosVideoIdStatusGetResponse = GetVideoStatusApiVideosVideoIdStatusGetResponses[keyof GetVideoStatusApiVideosVideoIdStatusGetResponses];

export type UploadVideoGenericApiVideosUploadPostData = {
    body: BodyUploadVideoGenericApiVideosUploadPost;
    path?: never;
    query?: {
        /**
         * Series
         */
        series?: string;
    };
    url: '/api/videos/upload';
};

export type UploadVideoGenericApiVideosUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadVideoGenericApiVideosUploadPostError = UploadVideoGenericApiVideosUploadPostErrors[keyof UploadVideoGenericApiVideosUploadPostErrors];

export type UploadVideoGenericApiVideosUploadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadVideoToSeriesApiVideosUploadSeriesPostData = {
    body: BodyUploadVideoToSeriesApiVideosUploadSeriesPost;
    path: {
        /**
         * Series
         */
        series: string;
    };
    query?: never;
    url: '/api/videos/upload/{series}';
};

export type UploadVideoToSeriesApiVideosUploadSeriesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadVideoToSeriesApiVideosUploadSeriesPostError = UploadVideoToSeriesApiVideosUploadSeriesPostErrors[keyof UploadVideoToSeriesApiVideosUploadSeriesPostErrors];

export type UploadVideoToSeriesApiVideosUploadSeriesPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProcessChunkApiProcessChunkPostData = {
    body: ChunkProcessingRequest;
    path?: never;
    query?: never;
    url: '/api/process/chunk';
};

export type ProcessChunkApiProcessChunkPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProcessChunkApiProcessChunkPostError = ProcessChunkApiProcessChunkPostErrors[keyof ProcessChunkApiProcessChunkPostErrors];

export type ProcessChunkApiProcessChunkPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TranscribeVideoApiProcessTranscribePostData = {
    body: TranscribeRequest;
    path?: never;
    query?: never;
    url: '/api/process/transcribe';
};

export type TranscribeVideoApiProcessTranscribePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TranscribeVideoApiProcessTranscribePostError = TranscribeVideoApiProcessTranscribePostErrors[keyof TranscribeVideoApiProcessTranscribePostErrors];

export type TranscribeVideoApiProcessTranscribePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FilterSubtitlesApiProcessFilterSubtitlesPostData = {
    body: FilterRequest;
    path?: never;
    query?: never;
    url: '/api/process/filter-subtitles';
};

export type FilterSubtitlesApiProcessFilterSubtitlesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FilterSubtitlesApiProcessFilterSubtitlesPostError = FilterSubtitlesApiProcessFilterSubtitlesPostErrors[keyof FilterSubtitlesApiProcessFilterSubtitlesPostErrors];

export type FilterSubtitlesApiProcessFilterSubtitlesPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TranslateSubtitlesApiProcessTranslateSubtitlesPostData = {
    body: TranslateRequest;
    path?: never;
    query?: never;
    url: '/api/process/translate-subtitles';
};

export type TranslateSubtitlesApiProcessTranslateSubtitlesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TranslateSubtitlesApiProcessTranslateSubtitlesPostError = TranslateSubtitlesApiProcessTranslateSubtitlesPostErrors[keyof TranslateSubtitlesApiProcessTranslateSubtitlesPostErrors];

export type TranslateSubtitlesApiProcessTranslateSubtitlesPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PrepareEpisodeApiProcessPrepareEpisodePostData = {
    body: TranscribeRequest;
    path?: never;
    query?: never;
    url: '/api/process/prepare-episode';
};

export type PrepareEpisodeApiProcessPrepareEpisodePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PrepareEpisodeApiProcessPrepareEpisodePostError = PrepareEpisodeApiProcessPrepareEpisodePostErrors[keyof PrepareEpisodeApiProcessPrepareEpisodePostErrors];

export type PrepareEpisodeApiProcessPrepareEpisodePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FullPipelineApiProcessFullPipelinePostData = {
    body: FullPipelineRequest;
    path?: never;
    query?: never;
    url: '/api/process/full-pipeline';
};

export type FullPipelineApiProcessFullPipelinePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FullPipelineApiProcessFullPipelinePostError = FullPipelineApiProcessFullPipelinePostErrors[keyof FullPipelineApiProcessFullPipelinePostErrors];

export type FullPipelineApiProcessFullPipelinePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTaskProgressApiProcessProgressTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/process/progress/{task_id}';
};

export type GetTaskProgressApiProcessProgressTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskProgressApiProcessProgressTaskIdGetError = GetTaskProgressApiProcessProgressTaskIdGetErrors[keyof GetTaskProgressApiProcessProgressTaskIdGetErrors];

export type GetTaskProgressApiProcessProgressTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetVocabularyStatsApiVocabularyStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/vocabulary/stats';
};

export type GetVocabularyStatsApiVocabularyStatsGetResponses = {
    /**
     * Successful Response
     */
    200: VocabularyStats;
};

export type GetVocabularyStatsApiVocabularyStatsGetResponse = GetVocabularyStatsApiVocabularyStatsGetResponses[keyof GetVocabularyStatsApiVocabularyStatsGetResponses];

export type GetBlockingWordsApiVocabularyBlockingWordsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Video Path
         */
        video_path: string;
        /**
         * Segment Start
         */
        segment_start?: number;
        /**
         * Segment Duration
         */
        segment_duration?: number;
    };
    url: '/api/vocabulary/blocking-words';
};

export type GetBlockingWordsApiVocabularyBlockingWordsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBlockingWordsApiVocabularyBlockingWordsGetError = GetBlockingWordsApiVocabularyBlockingWordsGetErrors[keyof GetBlockingWordsApiVocabularyBlockingWordsGetErrors];

export type GetBlockingWordsApiVocabularyBlockingWordsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type MarkWordKnownApiVocabularyMarkKnownPostData = {
    body: MarkKnownRequest;
    path?: never;
    query?: never;
    url: '/api/vocabulary/mark-known';
};

export type MarkWordKnownApiVocabularyMarkKnownPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MarkWordKnownApiVocabularyMarkKnownPostError = MarkWordKnownApiVocabularyMarkKnownPostErrors[keyof MarkWordKnownApiVocabularyMarkKnownPostErrors];

export type MarkWordKnownApiVocabularyMarkKnownPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PreloadVocabularyApiVocabularyPreloadPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/vocabulary/preload';
};

export type PreloadVocabularyApiVocabularyPreloadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetLibraryStatsApiVocabularyLibraryStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/vocabulary/library/stats';
};

export type GetLibraryStatsApiVocabularyLibraryStatsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetVocabularyLevelApiVocabularyLibraryLevelGetData = {
    body?: never;
    path: {
        /**
         * Level
         */
        level: string;
    };
    query?: never;
    url: '/api/vocabulary/library/{level}';
};

export type GetVocabularyLevelApiVocabularyLibraryLevelGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVocabularyLevelApiVocabularyLibraryLevelGetError = GetVocabularyLevelApiVocabularyLibraryLevelGetErrors[keyof GetVocabularyLevelApiVocabularyLibraryLevelGetErrors];

export type GetVocabularyLevelApiVocabularyLibraryLevelGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BulkMarkLevelApiVocabularyLibraryBulkMarkPostData = {
    body: BulkMarkRequest;
    path?: never;
    query?: never;
    url: '/api/vocabulary/library/bulk-mark';
};

export type BulkMarkLevelApiVocabularyLibraryBulkMarkPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BulkMarkLevelApiVocabularyLibraryBulkMarkPostError = BulkMarkLevelApiVocabularyLibraryBulkMarkPostErrors[keyof BulkMarkLevelApiVocabularyLibraryBulkMarkPostErrors];

export type BulkMarkLevelApiVocabularyLibraryBulkMarkPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProfileGetApiProfileGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/profile';
};

export type ProfileGetApiProfileGetResponses = {
    /**
     * Successful Response
     */
    200: UserProfile;
};

export type ProfileGetApiProfileGetResponse = ProfileGetApiProfileGetResponses[keyof ProfileGetApiProfileGetResponses];

export type ProfileGetSupportedLanguagesApiProfileLanguagesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/profile/languages';
};

export type ProfileGetSupportedLanguagesApiProfileLanguagesGetResponses = {
    /**
     * Response Profile Get Supported Languages Api Profile Languages Get
     * Successful Response
     */
    200: {
        [key: string]: {
            [key: string]: string;
        };
    };
};

export type ProfileGetSupportedLanguagesApiProfileLanguagesGetResponse = ProfileGetSupportedLanguagesApiProfileLanguagesGetResponses[keyof ProfileGetSupportedLanguagesApiProfileLanguagesGetResponses];

export type ProfileUpdateLanguagesApiProfileLanguagesPutData = {
    body: LanguagePreferences;
    path?: never;
    query?: never;
    url: '/api/profile/languages';
};

export type ProfileUpdateLanguagesApiProfileLanguagesPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProfileUpdateLanguagesApiProfileLanguagesPutError = ProfileUpdateLanguagesApiProfileLanguagesPutErrors[keyof ProfileUpdateLanguagesApiProfileLanguagesPutErrors];

export type ProfileUpdateLanguagesApiProfileLanguagesPutResponses = {
    /**
     * Response Profile Update Languages Api Profile Languages Put
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ProfileUpdateLanguagesApiProfileLanguagesPutResponse = ProfileUpdateLanguagesApiProfileLanguagesPutResponses[keyof ProfileUpdateLanguagesApiProfileLanguagesPutResponses];

export type ProfileGetSettingsApiProfileSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/profile/settings';
};

export type ProfileGetSettingsApiProfileSettingsGetResponses = {
    /**
     * Successful Response
     */
    200: UserSettings;
};

export type ProfileGetSettingsApiProfileSettingsGetResponse = ProfileGetSettingsApiProfileSettingsGetResponses[keyof ProfileGetSettingsApiProfileSettingsGetResponses];

export type ProfileUpdateSettingsApiProfileSettingsPutData = {
    body: UserSettings;
    path?: never;
    query?: never;
    url: '/api/profile/settings';
};

export type ProfileUpdateSettingsApiProfileSettingsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProfileUpdateSettingsApiProfileSettingsPutError = ProfileUpdateSettingsApiProfileSettingsPutErrors[keyof ProfileUpdateSettingsApiProfileSettingsPutErrors];

export type ProfileUpdateSettingsApiProfileSettingsPutResponses = {
    /**
     * Successful Response
     */
    200: UserSettings;
};

export type ProfileUpdateSettingsApiProfileSettingsPutResponse = ProfileUpdateSettingsApiProfileSettingsPutResponses[keyof ProfileUpdateSettingsApiProfileSettingsPutResponses];

export type LogsReceiveFrontendApiLogsFrontendPostData = {
    body: LogBatch;
    path?: never;
    query?: never;
    url: '/api/logs/frontend';
};

export type LogsReceiveFrontendApiLogsFrontendPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogsReceiveFrontendApiLogsFrontendPostError = LogsReceiveFrontendApiLogsFrontendPostErrors[keyof LogsReceiveFrontendApiLogsFrontendPostErrors];

export type LogsReceiveFrontendApiLogsFrontendPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LogsListFilesApiLogsListGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/logs/list';
};

export type LogsListFilesApiLogsListGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LogsDownloadFileApiLogsDownloadFilenameGetData = {
    body?: never;
    path: {
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/api/logs/download/{filename}';
};

export type LogsDownloadFileApiLogsDownloadFilenameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogsDownloadFileApiLogsDownloadFilenameGetError = LogsDownloadFileApiLogsDownloadFilenameGetErrors[keyof LogsDownloadFileApiLogsDownloadFilenameGetErrors];

export type LogsDownloadFileApiLogsDownloadFilenameGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProgressGetUserApiProgressUserGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/progress/user';
};

export type ProgressGetUserApiProgressUserGetResponses = {
    /**
     * Successful Response
     */
    200: UserProgress;
};

export type ProgressGetUserApiProgressUserGetResponse = ProgressGetUserApiProgressUserGetResponses[keyof ProgressGetUserApiProgressUserGetResponses];

export type ProgressUpdateUserApiProgressUpdatePostData = {
    /**
     * Progress Update
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/progress/update';
};

export type ProgressUpdateUserApiProgressUpdatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProgressUpdateUserApiProgressUpdatePostError = ProgressUpdateUserApiProgressUpdatePostErrors[keyof ProgressUpdateUserApiProgressUpdatePostErrors];

export type ProgressUpdateUserApiProgressUpdatePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProgressGetDailyApiProgressDailyGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Days
         */
        days?: number;
    };
    url: '/api/progress/daily';
};

export type ProgressGetDailyApiProgressDailyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProgressGetDailyApiProgressDailyGetError = ProgressGetDailyApiProgressDailyGetErrors[keyof ProgressGetDailyApiProgressDailyGetErrors];

export type ProgressGetDailyApiProgressDailyGetResponses = {
    /**
     * Response Progress Get Daily Api Progress Daily Get
     * Successful Response
     */
    200: Array<DailyProgress>;
};

export type ProgressGetDailyApiProgressDailyGetResponse = ProgressGetDailyApiProgressDailyGetResponses[keyof ProgressGetDailyApiProgressDailyGetResponses];

export type GameStartSessionApiGameStartPostData = {
    body: StartGameRequest;
    path?: never;
    query?: never;
    url: '/api/game/start';
};

export type GameStartSessionApiGameStartPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GameStartSessionApiGameStartPostError = GameStartSessionApiGameStartPostErrors[keyof GameStartSessionApiGameStartPostErrors];

export type GameStartSessionApiGameStartPostResponses = {
    /**
     * Successful Response
     */
    200: GameSession;
};

export type GameStartSessionApiGameStartPostResponse = GameStartSessionApiGameStartPostResponses[keyof GameStartSessionApiGameStartPostResponses];

export type GameGetSessionApiGameSessionSessionIdGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/game/session/{session_id}';
};

export type GameGetSessionApiGameSessionSessionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GameGetSessionApiGameSessionSessionIdGetError = GameGetSessionApiGameSessionSessionIdGetErrors[keyof GameGetSessionApiGameSessionSessionIdGetErrors];

export type GameGetSessionApiGameSessionSessionIdGetResponses = {
    /**
     * Successful Response
     */
    200: GameSession;
};

export type GameGetSessionApiGameSessionSessionIdGetResponse = GameGetSessionApiGameSessionSessionIdGetResponses[keyof GameGetSessionApiGameSessionSessionIdGetResponses];

export type GameSubmitAnswerApiGameAnswerPostData = {
    body: AnswerRequest;
    path?: never;
    query?: never;
    url: '/api/game/answer';
};

export type GameSubmitAnswerApiGameAnswerPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GameSubmitAnswerApiGameAnswerPostError = GameSubmitAnswerApiGameAnswerPostErrors[keyof GameSubmitAnswerApiGameAnswerPostErrors];

export type GameSubmitAnswerApiGameAnswerPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GameGetUserSessionsApiGameSessionsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/game/sessions';
};

export type GameGetUserSessionsApiGameSessionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GameGetUserSessionsApiGameSessionsGetError = GameGetUserSessionsApiGameSessionsGetErrors[keyof GameGetUserSessionsApiGameSessionsGetErrors];

export type GameGetUserSessionsApiGameSessionsGetResponses = {
    /**
     * Response Game Get User Sessions Api Game Sessions Get
     * Successful Response
     */
    200: Array<GameSession>;
};

export type GameGetUserSessionsApiGameSessionsGetResponse = GameGetUserSessionsApiGameSessionsGetResponses[keyof GameGetUserSessionsApiGameSessionsGetResponses];

export type ParseSrtContentApiSrtParsePostData = {
    body: ParseSrtRequest;
    path?: never;
    query?: never;
    url: '/api/srt/parse';
};

export type ParseSrtContentApiSrtParsePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ParseSrtContentApiSrtParsePostError = ParseSrtContentApiSrtParsePostErrors[keyof ParseSrtContentApiSrtParsePostErrors];

export type ParseSrtContentApiSrtParsePostResponses = {
    /**
     * Successful Response
     */
    200: ParseSrtResponse;
};

export type ParseSrtContentApiSrtParsePostResponse = ParseSrtContentApiSrtParsePostResponses[keyof ParseSrtContentApiSrtParsePostResponses];

export type ParseSrtFileApiSrtParseFilePostData = {
    body: BodyParseSrtFileApiSrtParseFilePost;
    path?: never;
    query?: never;
    url: '/api/srt/parse-file';
};

export type ParseSrtFileApiSrtParseFilePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ParseSrtFileApiSrtParseFilePostError = ParseSrtFileApiSrtParseFilePostErrors[keyof ParseSrtFileApiSrtParseFilePostErrors];

export type ParseSrtFileApiSrtParseFilePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ConvertToSrtApiSrtConvertToSrtPostData = {
    body: ConvertToSrtRequest;
    path?: never;
    query?: never;
    url: '/api/srt/convert-to-srt';
};

export type ConvertToSrtApiSrtConvertToSrtPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConvertToSrtApiSrtConvertToSrtPostError = ConvertToSrtApiSrtConvertToSrtPostErrors[keyof ConvertToSrtApiSrtConvertToSrtPostErrors];

export type ConvertToSrtApiSrtConvertToSrtPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ValidateSrtContentApiSrtValidateGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Content
         */
        content: string;
    };
    url: '/api/srt/validate';
};

export type ValidateSrtContentApiSrtValidateGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateSrtContentApiSrtValidateGetError = ValidateSrtContentApiSrtValidateGetErrors[keyof ValidateSrtContentApiSrtValidateGetErrors];

export type ValidateSrtContentApiSrtValidateGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};
