"""Initial migration

Revision ID: 879b4bfbd98e
Revises: 
Create Date: 2025-09-15 12:00:35.628523

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '879b4bfbd98e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schema_migrations')
    op.drop_index(op.f('idx_sessions_expires'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('idx_user_progress_word'), table_name='user_progress')
    op.drop_table('user_progress')
    op.alter_column('processing_sessions', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('processing_sessions', 'processing_time_seconds',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('processing_sessions', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index('idx_sessions_start_time', 'processing_sessions', ['created_at'], unique=False)
    op.create_index('idx_sessions_type', 'processing_sessions', ['content_type'], unique=False)
    op.create_unique_constraint(None, 'processing_sessions', ['session_id'])
    op.alter_column('session_word_discoveries', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index('idx_swd_word', 'session_word_discoveries', ['word'], unique=False)
    op.drop_constraint(None, 'session_word_discoveries', type_='foreignkey')
    op.create_foreign_key(None, 'session_word_discoveries', 'processing_sessions', ['session_id'], ['session_id'])
    op.alter_column('unknown_words', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('unknown_words', 'first_encountered',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('unknown_words', 'last_encountered',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index('idx_unknown_words_first_encountered', 'unknown_words', [sa.literal_column('first_encountered DESC')], unique=False)
    op.create_index('idx_unknown_words_language', 'unknown_words', ['language'], unique=False)
    op.create_index('idx_unknown_words_last_encountered', 'unknown_words', [sa.literal_column('last_encountered DESC')], unique=False)
    op.create_index('idx_unknown_words_word_lang', 'unknown_words', ['word', 'language'], unique=False)
    op.alter_column('user_learning_progress', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('user_learning_progress', 'learned_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('user_learning_progress', 'last_reviewed',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index('idx_ulp_confidence', 'user_learning_progress', [sa.literal_column('confidence_level DESC')], unique=False)
    op.create_index('idx_ulp_last_reviewed', 'user_learning_progress', ['last_reviewed'], unique=False)
    op.create_index('idx_ulp_review_count', 'user_learning_progress', [sa.literal_column('review_count DESC')], unique=False)
    op.create_index('idx_ulp_word_id', 'user_learning_progress', ['word_id'], unique=False)
    op.drop_constraint(None, 'user_learning_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_learning_progress', 'vocabulary', ['word_id'], ['id'])
    op.alter_column('user_sessions', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('user_sessions', 'expires_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('user_sessions', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('user_sessions', 'last_used',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index('idx_user_sessions_active', 'user_sessions', ['is_active'], unique=False)
    op.create_index('idx_user_sessions_expires', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('idx_user_sessions_token', 'user_sessions', ['session_token'], unique=False)
    op.create_index('idx_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'user_sessions', ['session_token'])
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'last_login',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index('idx_users_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_created', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_last_login', 'users', ['last_login'], unique=False)
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'subtitle_language')
    op.alter_column('vocabulary', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('vocabulary', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('vocabulary', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index('idx_vocabulary_created', 'vocabulary', ['created_at'], unique=False)
    op.alter_column('word_categories', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('word_categories', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('word_categories', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_unique_constraint(None, 'word_categories', ['name'])
    op.alter_column('word_category_associations', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('word_category_associations', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_constraint(None, 'word_category_associations', type_='foreignkey')
    op.drop_constraint(None, 'word_category_associations', type_='foreignkey')
    op.create_foreign_key(None, 'word_category_associations', 'word_categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'word_category_associations', 'vocabulary', ['word_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'word_category_associations', type_='foreignkey')
    op.drop_constraint(None, 'word_category_associations', type_='foreignkey')
    op.create_foreign_key(None, 'word_category_associations', 'vocabulary', ['word_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'word_category_associations', 'word_categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.alter_column('word_category_associations', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('word_category_associations', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'word_categories', type_='unique')
    op.alter_column('word_categories', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('word_categories', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('word_categories', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index('idx_vocabulary_created', table_name='vocabulary')
    op.alter_column('vocabulary', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('vocabulary', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('vocabulary', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('users', sa.Column('subtitle_language', sa.TEXT(), server_default=sa.text("'en'"), nullable=True))
    op.add_column('users', sa.Column('preferred_language', sa.TEXT(), server_default=sa.text("'de'"), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('idx_users_last_login', table_name='users')
    op.drop_index('idx_users_created', table_name='users')
    op.drop_index('idx_users_active', table_name='users')
    op.alter_column('users', 'last_login',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_sessions', type_='unique')
    op.drop_index('idx_user_sessions_user_id', table_name='user_sessions')
    op.drop_index('idx_user_sessions_token', table_name='user_sessions')
    op.drop_index('idx_user_sessions_expires', table_name='user_sessions')
    op.drop_index('idx_user_sessions_active', table_name='user_sessions')
    op.alter_column('user_sessions', 'last_used',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('user_sessions', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('user_sessions', 'expires_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('user_sessions', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'user_learning_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_learning_progress', 'vocabulary', ['word_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_ulp_word_id', table_name='user_learning_progress')
    op.drop_index('idx_ulp_review_count', table_name='user_learning_progress')
    op.drop_index('idx_ulp_last_reviewed', table_name='user_learning_progress')
    op.drop_index('idx_ulp_confidence', table_name='user_learning_progress')
    op.alter_column('user_learning_progress', 'last_reviewed',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('user_learning_progress', 'learned_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('user_learning_progress', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index('idx_unknown_words_word_lang', table_name='unknown_words')
    op.drop_index('idx_unknown_words_last_encountered', table_name='unknown_words')
    op.drop_index('idx_unknown_words_language', table_name='unknown_words')
    op.drop_index('idx_unknown_words_first_encountered', table_name='unknown_words')
    op.alter_column('unknown_words', 'last_encountered',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('unknown_words', 'first_encountered',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('unknown_words', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'session_word_discoveries', type_='foreignkey')
    op.create_foreign_key(None, 'session_word_discoveries', 'processing_sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.drop_index('idx_swd_word', table_name='session_word_discoveries')
    op.alter_column('session_word_discoveries', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'processing_sessions', type_='unique')
    op.drop_index('idx_sessions_type', table_name='processing_sessions')
    op.drop_index('idx_sessions_start_time', table_name='processing_sessions')
    op.alter_column('processing_sessions', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('processing_sessions', 'processing_time_seconds',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('processing_sessions', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_table('user_progress',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('word_id', sa.INTEGER(), nullable=False),
    sa.Column('is_known', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('confidence_level', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('last_seen', sa.TIMESTAMP(), nullable=True),
    sa.Column('times_seen', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['vocabulary.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id')
    )
    op.create_index(op.f('idx_user_progress_word'), 'user_progress', ['word_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_sessions_expires'), 'sessions', ['expires_at'], unique=False)
    op.create_table('schema_migrations',
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('applied_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('version')
    )
    # ### end Alembic commands ###
