name: "Setup Python Environment"
description: "Configure Python environment with caching and dependencies"
inputs:
  python-version:
    description: "Python version to setup"
    required: false
    default: "3.11"
  working-directory:
    description: "Working directory for Python operations"
    required: false
    default: "./src/backend"
  requirements-file:
    description: "Requirements file to install"
    required: false
    default: "requirements.txt"
  cache-key:
    description: "Additional cache key suffix"
    required: false
    default: ""
  install-extras:
    description: "Extra packages to install"
    required: false
    default: ""

outputs:
  cache-hit:
    description: "Whether cache was hit"
    value: ${{ steps.cache.outputs.cache-hit }}
  python-path:
    description: "Path to Python executable"
    value: ${{ steps.setup-python.outputs.python-path }}

runs:
  using: "composite"
  steps:
    - name: Setup Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Get pip cache dir
      id: pip-cache-dir
      shell: bash
      run: echo "dir=$(python -m pip cache dir)" >> $GITHUB_OUTPUT

    - name: Cache pip dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pip-cache-dir.outputs.dir }}
        key: pip-${{ runner.os }}-py${{ inputs.python-version }}-${{ hashFiles(format('{0}/{1}', inputs.working-directory, inputs.requirements-file)) }}-${{ inputs.cache-key }}
        restore-keys: |
          pip-${{ runner.os }}-py${{ inputs.python-version }}-
          pip-${{ runner.os }}-

    - name: Upgrade pip
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: python -m pip install --upgrade pip

    - name: Install requirements
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -f "${{ inputs.requirements-file }}" ]; then
          echo "Installing dependencies from ${{ inputs.requirements-file }}..."
          pip install -r ${{ inputs.requirements-file }} 2>&1 | tee pip-install.log
          echo "Installation complete. Log saved to pip-install.log"
        else
          echo "Requirements file ${{ inputs.requirements-file }} not found, skipping..."
        fi

    - name: Install extra packages
      if: inputs.install-extras != ''
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pip install ${{ inputs.install-extras }}

    - name: Display Python info
      shell: bash
      run: |
        echo "Python version: $(python --version)"
        echo "Python path: $(which python)"
        echo "Pip version: $(pip --version)"
        echo "Installed packages:"
        pip list --format=columns | head -20 || true
