// This file is auto-generated by @hey-api/openapi-ts

export const $AddCustomWordRequest = {
    properties: {
        word: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Word',
            description: 'The word to add'
        },
        lemma: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lemma',
            description: 'Base form of the word'
        },
        language: {
            type: 'string',
            title: 'Language',
            description: 'Language code',
            default: 'de'
        },
        translation: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Translation',
            description: "Translation in user's native language"
        },
        part_of_speech: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Part Of Speech',
            description: 'Part of speech'
        },
        gender: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gender',
            description: 'Gender (for nouns)'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes',
            description: 'User notes'
        }
    },
    type: 'object',
    required: ['word'],
    title: 'AddCustomWordRequest',
    description: 'Request to add a custom user-defined vocabulary word'
} as const;

export const $AnswerRequest = {
    properties: {
        session_id: {
            type: 'string',
            title: 'Session Id'
        },
        question_id: {
            type: 'string',
            title: 'Question Id'
        },
        question_type: {
            type: 'string',
            title: 'Question Type',
            default: 'multiple_choice'
        },
        user_answer: {
            type: 'string',
            title: 'User Answer'
        },
        correct_answer: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Correct Answer'
        },
        points: {
            type: 'integer',
            title: 'Points',
            default: 10
        }
    },
    type: 'object',
    required: ['session_id', 'question_id', 'user_answer'],
    title: 'AnswerRequest',
    description: 'Request model for submitting an answer'
} as const;

export const $BearerResponse = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type'
        }
    },
    type: 'object',
    required: ['access_token', 'token_type'],
    title: 'BearerResponse'
} as const;

export const $Body_auth_jwt_login_api_auth_login_post = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_auth_jwt_login_api_auth_login_post'
} as const;

export const $Body_parse_srt_file_api_srt_parse_file_post = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_parse_srt_file_api_srt_parse_file_post'
} as const;

export const $Body_upload_subtitle_api_videos_subtitle_upload_post = {
    properties: {
        subtitle_file: {
            type: 'string',
            format: 'binary',
            title: 'Subtitle File'
        }
    },
    type: 'object',
    required: ['subtitle_file'],
    title: 'Body_upload_subtitle_api_videos_subtitle_upload_post'
} as const;

export const $Body_upload_video_generic_api_videos_upload_post = {
    properties: {
        video_file: {
            type: 'string',
            format: 'binary',
            title: 'Video File'
        }
    },
    type: 'object',
    required: ['video_file'],
    title: 'Body_upload_video_generic_api_videos_upload_post'
} as const;

export const $Body_upload_video_to_series_api_videos_upload__series__post = {
    properties: {
        video_file: {
            type: 'string',
            format: 'binary',
            title: 'Video File'
        }
    },
    type: 'object',
    required: ['video_file'],
    title: 'Body_upload_video_to_series_api_videos_upload__series__post'
} as const;

export const $BulkMarkLevelRequest = {
    properties: {
        level: {
            type: 'string',
            pattern: '^(A1|A2|B1|B2|C1|C2)$',
            title: 'Level'
        },
        target_language: {
            type: 'string',
            title: 'Target Language',
            description: 'Target language code',
            default: 'de'
        },
        known: {
            type: 'boolean',
            title: 'Known',
            description: 'Whether to mark as known'
        }
    },
    type: 'object',
    required: ['level', 'known'],
    title: 'BulkMarkLevelRequest',
    description: 'Request to mark all words in a level as known'
} as const;

export const $ChunkProcessingRequest = {
    properties: {
        video_path: {
            type: 'string',
            minLength: 1,
            title: 'Video Path',
            description: 'Path to the video file to process'
        },
        start_time: {
            type: 'number',
            minimum: 0,
            title: 'Start Time',
            description: 'Start time of the chunk in seconds'
        },
        end_time: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'End Time',
            description: 'End time of the chunk in seconds'
        }
    },
    type: 'object',
    required: ['video_path', 'start_time', 'end_time'],
    title: 'ChunkProcessingRequest',
    example: {
        end_time: 180,
        start_time: 120.5,
        video_path: '/videos/Superstore/S01/E01.mp4'
    }
} as const;

export const $ConvertToSRTRequest = {
    properties: {
        segments: {
            items: {
                '$ref': '#/components/schemas/SRTSegmentResponse'
            },
            type: 'array',
            title: 'Segments'
        }
    },
    type: 'object',
    required: ['segments'],
    title: 'ConvertToSRTRequest',
    description: 'Request model for converting segments to SRT format.'
} as const;

export const $CreateVocabularyRequest = {
    properties: {
        word: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Word',
            description: 'The vocabulary word'
        },
        translation: {
            type: 'string',
            maxLength: 200,
            minLength: 1,
            title: 'Translation',
            description: 'Translation of the word'
        },
        difficulty_level: {
            type: 'string',
            title: 'Difficulty Level',
            description: 'Difficulty level (beginner/intermediate/advanced)',
            default: 'beginner'
        },
        language: {
            type: 'string',
            title: 'Language',
            description: 'Language code',
            default: 'de'
        }
    },
    type: 'object',
    required: ['word', 'translation'],
    title: 'CreateVocabularyRequest',
    description: 'Request to create test vocabulary (for E2E tests)'
} as const;

export const $DailyProgress = {
    properties: {
        date: {
            type: 'string',
            title: 'Date'
        },
        videos_watched: {
            type: 'integer',
            title: 'Videos Watched',
            default: 0
        },
        watch_time: {
            type: 'number',
            title: 'Watch Time',
            default: 0
        },
        vocabulary_learned: {
            type: 'integer',
            title: 'Vocabulary Learned',
            default: 0
        },
        goals_completed: {
            type: 'integer',
            title: 'Goals Completed',
            default: 0
        },
        experience_gained: {
            type: 'integer',
            title: 'Experience Gained',
            default: 0
        }
    },
    type: 'object',
    required: ['date'],
    title: 'DailyProgress',
    description: 'Daily progress model'
} as const;

export const $ErrorModel = {
    properties: {
        detail: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                }
            ],
            title: 'Detail'
        }
    },
    type: 'object',
    required: ['detail'],
    title: 'ErrorModel'
} as const;

export const $FilterRequest = {
    properties: {
        video_path: {
            type: 'string',
            minLength: 1,
            title: 'Video Path',
            description: 'Path to the video file to filter subtitles for'
        }
    },
    type: 'object',
    required: ['video_path'],
    title: 'FilterRequest'
} as const;

export const $FrontendLogBatch = {
    properties: {
        logs: {
            items: {
                '$ref': '#/components/schemas/FrontendLogEntry'
            },
            type: 'array',
            title: 'Logs'
        }
    },
    type: 'object',
    required: ['logs'],
    title: 'FrontendLogBatch'
} as const;

export const $FrontendLogEntry = {
    properties: {
        timestamp: {
            type: 'string',
            title: 'Timestamp'
        },
        level: {
            type: 'string',
            title: 'Level'
        },
        category: {
            type: 'string',
            title: 'Category'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        data: {
            title: 'Data'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        },
        stack: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stack'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        userAgent: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Useragent'
        },
        userId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Userid'
        }
    },
    type: 'object',
    required: ['timestamp', 'level', 'category', 'message'],
    title: 'FrontendLogEntry'
} as const;

export const $FullPipelineRequest = {
    properties: {
        video_path: {
            type: 'string',
            minLength: 1,
            title: 'Video Path',
            description: 'Path to the video file to process'
        },
        source_lang: {
            type: 'string',
            maxLength: 5,
            minLength: 2,
            pattern: '^[a-z]{2}(-[A-Z]{2})?$',
            title: 'Source Lang',
            description: "Source language code (e.g., 'de', 'en-US')",
            default: 'de'
        },
        target_lang: {
            type: 'string',
            maxLength: 5,
            minLength: 2,
            pattern: '^[a-z]{2}(-[A-Z]{2})?$',
            title: 'Target Lang',
            description: "Target language code (e.g., 'en', 'de-DE')",
            default: 'en'
        }
    },
    type: 'object',
    required: ['video_path'],
    title: 'FullPipelineRequest'
} as const;

export const $GameDifficulty = {
    type: 'string',
    enum: ['beginner', 'intermediate', 'advanced'],
    title: 'GameDifficulty',
    description: 'Game difficulty levels'
} as const;

export const $GameSession = {
    properties: {
        session_id: {
            type: 'string',
            title: 'Session Id'
        },
        user_id: {
            type: 'string',
            title: 'User Id'
        },
        game_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/GameType'
                },
                {
                    type: 'string'
                }
            ],
            title: 'Game Type'
        },
        difficulty: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/GameDifficulty'
                },
                {
                    type: 'string'
                }
            ],
            title: 'Difficulty',
            default: 'intermediate'
        },
        video_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Video Id'
        },
        started_at: {
            type: 'string',
            format: 'date-time',
            title: 'Started At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/GameSessionStatus'
                },
                {
                    type: 'string'
                }
            ],
            title: 'Status',
            default: 'active'
        },
        score: {
            type: 'integer',
            title: 'Score',
            default: 0
        },
        max_score: {
            type: 'integer',
            title: 'Max Score',
            default: 100
        },
        questions_answered: {
            type: 'integer',
            title: 'Questions Answered',
            default: 0
        },
        correct_answers: {
            type: 'integer',
            title: 'Correct Answers',
            default: 0
        },
        current_question: {
            type: 'integer',
            title: 'Current Question',
            default: 0
        },
        total_questions: {
            type: 'integer',
            title: 'Total Questions',
            default: 10
        },
        session_data: {
            additionalProperties: true,
            type: 'object',
            title: 'Session Data'
        }
    },
    type: 'object',
    required: ['session_id', 'user_id', 'game_type', 'started_at'],
    title: 'GameSession',
    description: 'Game session model'
} as const;

export const $GameSessionStatus = {
    type: 'string',
    enum: ['active', 'completed', 'paused', 'abandoned'],
    title: 'GameSessionStatus',
    description: 'Game session statuses'
} as const;

export const $GameType = {
    type: 'string',
    enum: ['vocabulary', 'listening', 'comprehension'],
    title: 'GameType',
    description: 'Types of game sessions'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $LanguagePreferences = {
    properties: {
        native_language: {
            type: 'string',
            title: 'Native Language'
        },
        target_language: {
            type: 'string',
            title: 'Target Language'
        }
    },
    type: 'object',
    required: ['native_language', 'target_language'],
    title: 'LanguagePreferences',
    description: 'Language preference update model'
} as const;

export const $MarkKnownRequest = {
    properties: {
        concept_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Concept Id',
            description: 'The concept ID to mark (optional)'
        },
        word: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Word',
            description: 'The word text (optional)'
        },
        lemma: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lemma',
            description: 'The word lemma (optional)'
        },
        language: {
            type: 'string',
            title: 'Language',
            description: 'Language code',
            default: 'de'
        },
        known: {
            type: 'boolean',
            title: 'Known',
            description: 'Whether to mark as known'
        }
    },
    type: 'object',
    required: ['known'],
    title: 'MarkKnownRequest',
    description: 'Request to mark a word as known'
} as const;

export const $ParseSRTRequest = {
    properties: {
        content: {
            type: 'string',
            title: 'Content'
        }
    },
    type: 'object',
    required: ['content'],
    title: 'ParseSRTRequest',
    description: 'Request model for parsing SRT content.'
} as const;

export const $ParseSRTResponse = {
    properties: {
        segments: {
            items: {
                '$ref': '#/components/schemas/SRTSegmentResponse'
            },
            type: 'array',
            title: 'Segments'
        },
        total_segments: {
            type: 'integer',
            title: 'Total Segments'
        },
        duration: {
            type: 'number',
            title: 'Duration'
        }
    },
    type: 'object',
    required: ['segments', 'total_segments', 'duration'],
    title: 'ParseSRTResponse',
    description: 'Response model for parsed SRT data.'
} as const;

export const $ProcessingStatus = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        progress: {
            type: 'number',
            title: 'Progress'
        },
        current_step: {
            type: 'string',
            title: 'Current Step'
        },
        message: {
            type: 'string',
            title: 'Message',
            default: ''
        },
        subtitle_path: {
            type: 'string',
            title: 'Subtitle Path',
            default: ''
        }
    },
    type: 'object',
    required: ['status', 'progress', 'current_step'],
    title: 'ProcessingStatus'
} as const;

export const $SRTSegmentResponse = {
    properties: {
        index: {
            type: 'integer',
            title: 'Index'
        },
        start_time: {
            type: 'number',
            title: 'Start Time'
        },
        end_time: {
            type: 'number',
            title: 'End Time'
        },
        text: {
            type: 'string',
            title: 'Text'
        },
        original_text: {
            type: 'string',
            title: 'Original Text',
            default: ''
        },
        translation: {
            type: 'string',
            title: 'Translation',
            default: ''
        }
    },
    type: 'object',
    required: ['index', 'start_time', 'end_time', 'text'],
    title: 'SRTSegmentResponse',
    description: 'Response model for SRT segment data.'
} as const;

export const $SearchVocabularyRequest = {
    properties: {
        search_term: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Search Term'
        },
        language: {
            type: 'string',
            title: 'Language',
            description: 'Language code',
            default: 'de'
        },
        limit: {
            type: 'integer',
            maximum: 100,
            minimum: 1,
            title: 'Limit',
            default: 20
        }
    },
    type: 'object',
    required: ['search_term'],
    title: 'SearchVocabularyRequest',
    description: 'Request to search vocabulary'
} as const;

export const $SelectiveTranslationRequest = {
    properties: {
        srt_path: {
            type: 'string',
            minLength: 1,
            title: 'Srt Path',
            description: 'Path to the SRT subtitle file'
        },
        known_words: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Known Words',
            description: 'List of words that the user already knows'
        }
    },
    type: 'object',
    required: ['srt_path', 'known_words'],
    title: 'SelectiveTranslationRequest',
    example: {
        known_words: ['der', 'die', 'das', 'und', 'ist'],
        srt_path: '/subtitles/episode_german.srt'
    }
} as const;

export const $StartGameRequest = {
    properties: {
        game_type: {
            '$ref': '#/components/schemas/GameType'
        },
        difficulty: {
            '$ref': '#/components/schemas/GameDifficulty',
            default: 'intermediate'
        },
        video_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Video Id'
        },
        total_questions: {
            type: 'integer',
            maximum: 50,
            minimum: 1,
            title: 'Total Questions',
            default: 10
        }
    },
    type: 'object',
    required: ['game_type'],
    title: 'StartGameRequest',
    description: 'Request model for starting a game session'
} as const;

export const $TokenRefreshResponse = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        },
        expires_in: {
            type: 'integer',
            title: 'Expires In'
        }
    },
    type: 'object',
    required: ['access_token', 'refresh_token', 'expires_in'],
    title: 'TokenRefreshResponse',
    description: 'Response model for token refresh with rotation'
} as const;

export const $TranscribeRequest = {
    properties: {
        video_path: {
            type: 'string',
            minLength: 1,
            title: 'Video Path',
            description: 'Path to the video file to transcribe'
        }
    },
    type: 'object',
    required: ['video_path'],
    title: 'TranscribeRequest'
} as const;

export const $UserCreate = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser',
            default: false
        },
        is_verified: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Verified',
            default: false
        },
        username: {
            type: 'string',
            title: 'Username'
        }
    },
    type: 'object',
    required: ['email', 'password', 'username'],
    title: 'UserCreate'
} as const;

export const $UserProfile = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        is_admin: {
            type: 'boolean',
            title: 'Is Admin'
        },
        created_at: {
            type: 'string',
            title: 'Created At'
        },
        last_login: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Login'
        },
        native_language: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Native Language'
        },
        target_language: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Target Language'
        },
        language_runtime: {
            additionalProperties: true,
            type: 'object',
            title: 'Language Runtime'
        }
    },
    type: 'object',
    required: ['id', 'username', 'is_admin', 'created_at', 'native_language', 'target_language', 'language_runtime'],
    title: 'UserProfile',
    description: 'User profile response model'
} as const;

export const $UserProgress = {
    properties: {
        user_id: {
            type: 'string',
            title: 'User Id'
        },
        total_videos_watched: {
            type: 'integer',
            title: 'Total Videos Watched',
            default: 0
        },
        total_watch_time: {
            type: 'number',
            title: 'Total Watch Time',
            default: 0
        },
        vocabulary_learned: {
            type: 'integer',
            title: 'Vocabulary Learned',
            default: 0
        },
        current_streak: {
            type: 'integer',
            title: 'Current Streak',
            default: 0
        },
        longest_streak: {
            type: 'integer',
            title: 'Longest Streak',
            default: 0
        },
        level: {
            type: 'string',
            title: 'Level',
            default: 'Beginner'
        },
        experience_points: {
            type: 'integer',
            title: 'Experience Points',
            default: 0
        },
        daily_goals_completed: {
            type: 'integer',
            title: 'Daily Goals Completed',
            default: 0
        },
        weekly_goals_completed: {
            type: 'integer',
            title: 'Weekly Goals Completed',
            default: 0
        },
        last_activity: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Activity'
        },
        achievements: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Achievements',
            default: []
        },
        learning_stats: {
            additionalProperties: true,
            type: 'object',
            title: 'Learning Stats',
            default: {}
        }
    },
    type: 'object',
    required: ['user_id'],
    title: 'UserProgress',
    description: 'User progress model'
} as const;

export const $UserRead = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        created_at: {
            type: 'string',
            title: 'Created At'
        },
        last_login: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Login'
        }
    },
    type: 'object',
    required: ['id', 'email', 'username', 'created_at'],
    title: 'UserRead'
} as const;

export const $UserResponse = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id',
            description: 'Unique user identifier'
        },
        username: {
            type: 'string',
            maxLength: 50,
            minLength: 3,
            title: 'Username',
            description: 'Username'
        },
        email: {
            type: 'string',
            title: 'Email',
            description: 'User email address'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            description: 'Whether user has superuser privileges'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            description: 'Whether user account is active'
        },
        created_at: {
            type: 'string',
            title: 'Created At',
            description: 'Account creation timestamp (ISO format)'
        },
        last_login: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Login',
            description: 'Last login timestamp (ISO format)'
        }
    },
    type: 'object',
    required: ['id', 'username', 'email', 'is_superuser', 'is_active', 'created_at'],
    title: 'UserResponse',
    example: {
        created_at: '2024-01-15T10:30:00Z',
        email: 'john_doe@example.com',
        id: 1,
        is_active: true,
        is_superuser: false,
        last_login: '2024-01-20T14:45:00Z',
        username: 'john_doe'
    }
} as const;

export const $UserSettings = {
    properties: {
        theme: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Theme',
            default: 'light'
        },
        notifications_enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notifications Enabled',
            default: true
        },
        auto_play: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Auto Play',
            default: true
        },
        subtitle_size: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Subtitle Size',
            default: 'medium'
        },
        playback_speed: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Playback Speed',
            default: 1
        },
        vocabulary_difficulty: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vocabulary Difficulty',
            default: 'intermediate'
        },
        daily_goal: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Daily Goal',
            default: 10
        },
        language_preferences: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/LanguagePreferences'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'UserSettings',
    description: 'User settings model'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const $VideoInfo = {
    properties: {
        series: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Series',
            description: 'Name of the TV series'
        },
        season: {
            type: 'string',
            maxLength: 20,
            minLength: 1,
            title: 'Season',
            description: "Season identifier (e.g., 'S01', 'Season 1')"
        },
        episode: {
            type: 'string',
            maxLength: 20,
            minLength: 1,
            title: 'Episode',
            description: "Episode identifier (e.g., 'E01', 'Episode 1')"
        },
        title: {
            type: 'string',
            maxLength: 200,
            minLength: 1,
            title: 'Title',
            description: 'Episode title'
        },
        path: {
            type: 'string',
            minLength: 1,
            title: 'Path',
            description: 'File system path to the video file'
        },
        has_subtitles: {
            type: 'boolean',
            title: 'Has Subtitles',
            description: 'Whether subtitles are available for this video'
        },
        duration: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration',
            description: 'Video duration in seconds'
        }
    },
    type: 'object',
    required: ['series', 'season', 'episode', 'title', 'path', 'has_subtitles'],
    title: 'VideoInfo',
    example: {
        duration: 1320.5,
        episode: 'E01',
        has_subtitles: true,
        path: '/videos/Superstore/S01/E01.mp4',
        season: 'S01',
        series: 'Superstore',
        title: 'Pilot'
    }
} as const;

export const $VocabularyWord = {
    properties: {
        concept_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'integer'
                },
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Concept Id',
            description: 'Unique identifier (UUID, int, or string)'
        },
        word: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Word',
            description: 'The vocabulary word in target language'
        },
        translation: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Translation',
            description: "Translation in user's preferred language"
        },
        lemma: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lemma',
            description: 'Base form of the word'
        },
        difficulty_level: {
            type: 'string',
            pattern: '^(A1|A2|B1|B2|C1|C2)$',
            title: 'Difficulty Level',
            description: 'CEFR difficulty level'
        },
        semantic_category: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Semantic Category',
            description: 'Part of speech (noun, verb, adjective, etc.)'
        },
        domain: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Domain',
            description: 'Domain category (education, technology, etc.)'
        },
        gender: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gender',
            description: 'Gender (der/die/das for German, el/la for Spanish)'
        },
        plural_form: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Plural Form',
            description: 'Plural form if applicable'
        },
        pronunciation: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pronunciation',
            description: 'IPA or phonetic representation'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes',
            description: 'Grammar notes, usage notes, etc.'
        },
        known: {
            type: 'boolean',
            title: 'Known',
            description: 'Whether the user knows this word',
            default: false
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['word', 'difficulty_level'],
    title: 'VocabularyWord',
    description: 'Single vocabulary word with translations',
    example: {
        concept_id: '550e8400-e29b-41d4-a716-446655440000',
        difficulty_level: 'A1',
        domain: 'housing',
        gender: 'das',
        known: false,
        lemma: 'haus',
        semantic_category: 'noun',
        translation: 'house',
        word: 'Haus'
    }
} as const;